
error_src=
{
	src_0x01="Main control interface board A";
	src_0x02="Main control interface board B";
	src_0x03="IO expansion board";
};

stop_model=
{
	stop_model_0x00="Class 0 shutdown";
	stop_model_0x01="Class 1 shutdown";
	stop_model_0x02="Class 2 shutdown";
};

err_type=
{
	err_type_0x01="warning";
	err_type_0x02="error";
};

err_class=
{
	err_class_0x01="Joint error";
	err_class_0x02="Robot arm information error";
	err_class_0x03="Robot arm initialization error";
	err_class_0x04="Robot　arm safety error";
	err_class_0x05="Robot　arm system error";
};

err_class_0x01=
{
	joint_error_code_0x01="Overcurrent";
	joint_error_code_0x02="Overpressure";
	joint_error_code_0x03="Undervoltage";
	joint_error_code_0x04="Over temperature";
	joint_error_code_0x05="Hall error";
	joint_error_code_0x06="Encoder error";
	joint_error_code_0x07="Absolute encoder error";
	joint_error_code_0x08="Current detection error";
	joint_error_code_0x09="Encoder contamination";
	joint_error_code_0x0A="Encoder Z signal error";
	joint_error_code_0x0B="Encoder calibration failed";
	joint_error_code_0x0C="IMU sensor failure";
	joint_error_code_0x0D="Temperature sensor error";
	joint_error_code_0x0E="CAN bus communication error";
	joint_error_code_0x0F="Current error";
	joint_error_code_0x10="The current position is wrong";
	joint_error_code_0x11="Joint overspeed error";
	joint_error_code_0x12="Joint acceleration error";
	joint_error_code_0x13="Tracking accuracy error";
	joint_error_code_0x14="Target position overrange";
	joint_error_code_0x15="Target speed over range";
	joint_error_code_0x20="collision";
};


err_class_0x02=
{
	robot_info_error_code_0x01="Robot arm type error";
	robot_info_error_code_0x02="Accelerometer chip error";
	robot_info_error_code_0x03="Arm encoder line number error";
	robot_info_error_code_0x04="Enter drag teaching mode error";
	robot_info_error_code_0x05="Exit drag teaching mode error";
	robot_info_error_code_0x06="MAC data outage error";
};


err_class_0x03=
{
	robot_initialization_error_code_0x01="Failed to enable drive";
	robot_initialization_error_code_0x02="Enable automatic response failure";
	robot_initialization_error_code_0x03="Failed to enable current loop";
	robot_initialization_error_code_0x04="Failed to set target current";
	robot_initialization_error_code_0x05="Release brake failure";
	robot_initialization_error_code_0x06="Failed to enable location ring";
	robot_initialization_error_code_0x07="Failed to set maximum acceleration";
};

err_class_0x04=
{
	robot_safety_error_code_0x01="External emergency stop";
	robot_safety_error_code_0x02="System emergency stop";
	robot_safety_error_code_0x03="Teaching device emergency stop";
	robot_safety_error_code_0x04="Control cabinet emergency stop";
	robot_safety_error_code_0x05="Protection stop timeout";
	robot_safety_error_code_0x06="Reduced mode timeout";
	robot_safety_error_code_0x07="Operating frequency is too fast";
};

err_class_0x05=
{
	robot_system_error_code_0x01="MCU communication error";
	robot_system_error_code_0x02="RS485 communication error";
};


err_class_node=
{
	joint_error_node_0x00="Robot base";
	joint_error_node_0x01="Joint 1";
	joint_error_node_0x02="Joint 2";
	joint_error_node_0x03="Joint 3";
	joint_error_node_0x04="Joint 4";
	joint_error_node_0x05="Joint 5";
	joint_error_node_0x06="Joint 6";
	joint_error_node_0x07="Tool side";
};



