// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WorkstationGrpc.proto
// Protobuf C++ Version: 5.28.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_WorkstationGrpc_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_WorkstationGrpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/wrappers.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_WorkstationGrpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_WorkstationGrpc_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_WorkstationGrpc_2eproto;
namespace InoRobBusinessGrpc {
class GetPrintInfo_Request;
struct GetPrintInfo_RequestDefaultTypeInternal;
extern GetPrintInfo_RequestDefaultTypeInternal _GetPrintInfo_Request_default_instance_;
class GetPrintInfo_Response;
struct GetPrintInfo_ResponseDefaultTypeInternal;
extern GetPrintInfo_ResponseDefaultTypeInternal _GetPrintInfo_Response_default_instance_;
class GetWorkstationType_Response;
struct GetWorkstationType_ResponseDefaultTypeInternal;
extern GetWorkstationType_ResponseDefaultTypeInternal _GetWorkstationType_Response_default_instance_;
class PrintInfoItem_Grpc;
struct PrintInfoItem_GrpcDefaultTypeInternal;
extern PrintInfoItem_GrpcDefaultTypeInternal _PrintInfoItem_Grpc_default_instance_;
}  // namespace InoRobBusinessGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace InoRobBusinessGrpc {
enum WorkstationType_Grpc : int {
  Unknow_Grpc = 0,
  TP_Grpc = 1,
  PC_Grpc = 2,
  TP2_Grpc = 3,
  WorkstationType_Grpc_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  WorkstationType_Grpc_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool WorkstationType_Grpc_IsValid(int value);
extern const uint32_t WorkstationType_Grpc_internal_data_[];
constexpr WorkstationType_Grpc WorkstationType_Grpc_MIN = static_cast<WorkstationType_Grpc>(0);
constexpr WorkstationType_Grpc WorkstationType_Grpc_MAX = static_cast<WorkstationType_Grpc>(3);
constexpr int WorkstationType_Grpc_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
WorkstationType_Grpc_descriptor();
template <typename T>
const std::string& WorkstationType_Grpc_Name(T value) {
  static_assert(std::is_same<T, WorkstationType_Grpc>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to WorkstationType_Grpc_Name().");
  return WorkstationType_Grpc_Name(static_cast<WorkstationType_Grpc>(value));
}
template <>
inline const std::string& WorkstationType_Grpc_Name(WorkstationType_Grpc value) {
  return ::google::protobuf::internal::NameOfDenseEnum<WorkstationType_Grpc_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool WorkstationType_Grpc_Parse(absl::string_view name, WorkstationType_Grpc* value) {
  return ::google::protobuf::internal::ParseNamedEnum<WorkstationType_Grpc>(
      WorkstationType_Grpc_descriptor(), name, value);
}
enum InfoType_Grpc : int {
  MESSAGE_INFO_Grpc = 0,
  WARNING_INFO_Grpc = 1,
  ERROR_INFO_Grpc = 2,
  InfoType_Grpc_All = -1,
  InfoType_Grpc_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  InfoType_Grpc_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool InfoType_Grpc_IsValid(int value);
extern const uint32_t InfoType_Grpc_internal_data_[];
constexpr InfoType_Grpc InfoType_Grpc_MIN = static_cast<InfoType_Grpc>(-1);
constexpr InfoType_Grpc InfoType_Grpc_MAX = static_cast<InfoType_Grpc>(2);
constexpr int InfoType_Grpc_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
InfoType_Grpc_descriptor();
template <typename T>
const std::string& InfoType_Grpc_Name(T value) {
  static_assert(std::is_same<T, InfoType_Grpc>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to InfoType_Grpc_Name().");
  return InfoType_Grpc_Name(static_cast<InfoType_Grpc>(value));
}
template <>
inline const std::string& InfoType_Grpc_Name(InfoType_Grpc value) {
  return ::google::protobuf::internal::NameOfDenseEnum<InfoType_Grpc_descriptor,
                                                 -1, 2>(
      static_cast<int>(value));
}
inline bool InfoType_Grpc_Parse(absl::string_view name, InfoType_Grpc* value) {
  return ::google::protobuf::internal::ParseNamedEnum<InfoType_Grpc>(
      InfoType_Grpc_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class PrintInfoItem_Grpc final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.PrintInfoItem_Grpc) */ {
 public:
  inline PrintInfoItem_Grpc() : PrintInfoItem_Grpc(nullptr) {}
  ~PrintInfoItem_Grpc() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PrintInfoItem_Grpc(
      ::google::protobuf::internal::ConstantInitialized);

  inline PrintInfoItem_Grpc(const PrintInfoItem_Grpc& from) : PrintInfoItem_Grpc(nullptr, from) {}
  inline PrintInfoItem_Grpc(PrintInfoItem_Grpc&& from) noexcept
      : PrintInfoItem_Grpc(nullptr, std::move(from)) {}
  inline PrintInfoItem_Grpc& operator=(const PrintInfoItem_Grpc& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrintInfoItem_Grpc& operator=(PrintInfoItem_Grpc&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrintInfoItem_Grpc& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrintInfoItem_Grpc* internal_default_instance() {
    return reinterpret_cast<const PrintInfoItem_Grpc*>(
        &_PrintInfoItem_Grpc_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PrintInfoItem_Grpc& a, PrintInfoItem_Grpc& b) { a.Swap(&b); }
  inline void Swap(PrintInfoItem_Grpc* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrintInfoItem_Grpc* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrintInfoItem_Grpc* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<PrintInfoItem_Grpc>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PrintInfoItem_Grpc& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PrintInfoItem_Grpc& from) { PrintInfoItem_Grpc::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PrintInfoItem_Grpc* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.PrintInfoItem_Grpc"; }

 protected:
  explicit PrintInfoItem_Grpc(::google::protobuf::Arena* arena);
  PrintInfoItem_Grpc(::google::protobuf::Arena* arena, const PrintInfoItem_Grpc& from);
  PrintInfoItem_Grpc(::google::protobuf::Arena* arena, PrintInfoItem_Grpc&& from) noexcept
      : PrintInfoItem_Grpc(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDtFieldNumber = 2,
    kContFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // string dt = 2;
  void clear_dt() ;
  const std::string& dt() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_dt(Arg_&& arg, Args_... args);
  std::string* mutable_dt();
  PROTOBUF_NODISCARD std::string* release_dt();
  void set_allocated_dt(std::string* value);

  private:
  const std::string& _internal_dt() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dt(
      const std::string& value);
  std::string* _internal_mutable_dt();

  public:
  // bytes cont = 3;
  void clear_cont() ;
  const std::string& cont() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cont(Arg_&& arg, Args_... args);
  std::string* mutable_cont();
  PROTOBUF_NODISCARD std::string* release_cont();
  void set_allocated_cont(std::string* value);

  private:
  const std::string& _internal_cont() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cont(
      const std::string& value);
  std::string* _internal_mutable_cont();

  public:
  // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
  void clear_type() ;
  ::InoRobBusinessGrpc::InfoType_Grpc type() const;
  void set_type(::InoRobBusinessGrpc::InfoType_Grpc value);

  private:
  ::InoRobBusinessGrpc::InfoType_Grpc _internal_type() const;
  void _internal_set_type(::InoRobBusinessGrpc::InfoType_Grpc value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.PrintInfoItem_Grpc)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      48, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_PrintInfoItem_Grpc_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PrintInfoItem_Grpc& from_msg);
    ::google::protobuf::internal::ArenaStringPtr dt_;
    ::google::protobuf::internal::ArenaStringPtr cont_;
    int type_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WorkstationGrpc_2eproto;
};
// -------------------------------------------------------------------

class GetWorkstationType_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.GetWorkstationType_Response) */ {
 public:
  inline GetWorkstationType_Response() : GetWorkstationType_Response(nullptr) {}
  ~GetWorkstationType_Response() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetWorkstationType_Response(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetWorkstationType_Response(const GetWorkstationType_Response& from) : GetWorkstationType_Response(nullptr, from) {}
  inline GetWorkstationType_Response(GetWorkstationType_Response&& from) noexcept
      : GetWorkstationType_Response(nullptr, std::move(from)) {}
  inline GetWorkstationType_Response& operator=(const GetWorkstationType_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetWorkstationType_Response& operator=(GetWorkstationType_Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetWorkstationType_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetWorkstationType_Response* internal_default_instance() {
    return reinterpret_cast<const GetWorkstationType_Response*>(
        &_GetWorkstationType_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(GetWorkstationType_Response& a, GetWorkstationType_Response& b) { a.Swap(&b); }
  inline void Swap(GetWorkstationType_Response* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetWorkstationType_Response* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetWorkstationType_Response* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetWorkstationType_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetWorkstationType_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetWorkstationType_Response& from) { GetWorkstationType_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetWorkstationType_Response* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.GetWorkstationType_Response"; }

 protected:
  explicit GetWorkstationType_Response(::google::protobuf::Arena* arena);
  GetWorkstationType_Response(::google::protobuf::Arena* arena, const GetWorkstationType_Response& from);
  GetWorkstationType_Response(::google::protobuf::Arena* arena, GetWorkstationType_Response&& from) noexcept
      : GetWorkstationType_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWorkstationTypeFieldNumber = 1,
  };
  // .InoRobBusinessGrpc.WorkstationType_Grpc workstationType = 1;
  void clear_workstationtype() ;
  ::InoRobBusinessGrpc::WorkstationType_Grpc workstationtype() const;
  void set_workstationtype(::InoRobBusinessGrpc::WorkstationType_Grpc value);

  private:
  ::InoRobBusinessGrpc::WorkstationType_Grpc _internal_workstationtype() const;
  void _internal_set_workstationtype(::InoRobBusinessGrpc::WorkstationType_Grpc value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.GetWorkstationType_Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetWorkstationType_Response_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetWorkstationType_Response& from_msg);
    int workstationtype_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WorkstationGrpc_2eproto;
};
// -------------------------------------------------------------------

class GetPrintInfo_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.GetPrintInfo_Request) */ {
 public:
  inline GetPrintInfo_Request() : GetPrintInfo_Request(nullptr) {}
  ~GetPrintInfo_Request() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetPrintInfo_Request(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetPrintInfo_Request(const GetPrintInfo_Request& from) : GetPrintInfo_Request(nullptr, from) {}
  inline GetPrintInfo_Request(GetPrintInfo_Request&& from) noexcept
      : GetPrintInfo_Request(nullptr, std::move(from)) {}
  inline GetPrintInfo_Request& operator=(const GetPrintInfo_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPrintInfo_Request& operator=(GetPrintInfo_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPrintInfo_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPrintInfo_Request* internal_default_instance() {
    return reinterpret_cast<const GetPrintInfo_Request*>(
        &_GetPrintInfo_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GetPrintInfo_Request& a, GetPrintInfo_Request& b) { a.Swap(&b); }
  inline void Swap(GetPrintInfo_Request* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPrintInfo_Request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPrintInfo_Request* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetPrintInfo_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetPrintInfo_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetPrintInfo_Request& from) { GetPrintInfo_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetPrintInfo_Request* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.GetPrintInfo_Request"; }

 protected:
  explicit GetPrintInfo_Request(::google::protobuf::Arena* arena);
  GetPrintInfo_Request(::google::protobuf::Arena* arena, const GetPrintInfo_Request& from);
  GetPrintInfo_Request(::google::protobuf::Arena* arena, GetPrintInfo_Request&& from) noexcept
      : GetPrintInfo_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kNumFieldNumber = 2,
  };
  // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
  void clear_type() ;
  ::InoRobBusinessGrpc::InfoType_Grpc type() const;
  void set_type(::InoRobBusinessGrpc::InfoType_Grpc value);

  private:
  ::InoRobBusinessGrpc::InfoType_Grpc _internal_type() const;
  void _internal_set_type(::InoRobBusinessGrpc::InfoType_Grpc value);

  public:
  // uint32 num = 2;
  void clear_num() ;
  ::uint32_t num() const;
  void set_num(::uint32_t value);

  private:
  ::uint32_t _internal_num() const;
  void _internal_set_num(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.GetPrintInfo_Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetPrintInfo_Request_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetPrintInfo_Request& from_msg);
    int type_;
    ::uint32_t num_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WorkstationGrpc_2eproto;
};
// -------------------------------------------------------------------

class GetPrintInfo_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.GetPrintInfo_Response) */ {
 public:
  inline GetPrintInfo_Response() : GetPrintInfo_Response(nullptr) {}
  ~GetPrintInfo_Response() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetPrintInfo_Response(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetPrintInfo_Response(const GetPrintInfo_Response& from) : GetPrintInfo_Response(nullptr, from) {}
  inline GetPrintInfo_Response(GetPrintInfo_Response&& from) noexcept
      : GetPrintInfo_Response(nullptr, std::move(from)) {}
  inline GetPrintInfo_Response& operator=(const GetPrintInfo_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPrintInfo_Response& operator=(GetPrintInfo_Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetPrintInfo_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPrintInfo_Response* internal_default_instance() {
    return reinterpret_cast<const GetPrintInfo_Response*>(
        &_GetPrintInfo_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GetPrintInfo_Response& a, GetPrintInfo_Response& b) { a.Swap(&b); }
  inline void Swap(GetPrintInfo_Response* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPrintInfo_Response* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPrintInfo_Response* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetPrintInfo_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetPrintInfo_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetPrintInfo_Response& from) { GetPrintInfo_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetPrintInfo_Response* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.GetPrintInfo_Response"; }

 protected:
  explicit GetPrintInfo_Response(::google::protobuf::Arena* arena);
  GetPrintInfo_Response(::google::protobuf::Arena* arena, const GetPrintInfo_Response& from);
  GetPrintInfo_Response(::google::protobuf::Arena* arena, GetPrintInfo_Response&& from) noexcept
      : GetPrintInfo_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPrintInfoListFieldNumber = 1,
  };
  // repeated .InoRobBusinessGrpc.PrintInfoItem_Grpc printInfoList = 1;
  int printinfolist_size() const;
  private:
  int _internal_printinfolist_size() const;

  public:
  void clear_printinfolist() ;
  ::InoRobBusinessGrpc::PrintInfoItem_Grpc* mutable_printinfolist(int index);
  ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>* mutable_printinfolist();

  private:
  const ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>& _internal_printinfolist() const;
  ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>* _internal_mutable_printinfolist();
  public:
  const ::InoRobBusinessGrpc::PrintInfoItem_Grpc& printinfolist(int index) const;
  ::InoRobBusinessGrpc::PrintInfoItem_Grpc* add_printinfolist();
  const ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>& printinfolist() const;
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.GetPrintInfo_Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetPrintInfo_Response_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetPrintInfo_Response& from_msg);
    ::google::protobuf::RepeatedPtrField< ::InoRobBusinessGrpc::PrintInfoItem_Grpc > printinfolist_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WorkstationGrpc_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PrintInfoItem_Grpc

// .InoRobBusinessGrpc.InfoType_Grpc type = 1;
inline void PrintInfoItem_Grpc::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::InoRobBusinessGrpc::InfoType_Grpc PrintInfoItem_Grpc::type() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.PrintInfoItem_Grpc.type)
  return _internal_type();
}
inline void PrintInfoItem_Grpc::set_type(::InoRobBusinessGrpc::InfoType_Grpc value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.PrintInfoItem_Grpc.type)
}
inline ::InoRobBusinessGrpc::InfoType_Grpc PrintInfoItem_Grpc::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::InoRobBusinessGrpc::InfoType_Grpc>(_impl_.type_);
}
inline void PrintInfoItem_Grpc::_internal_set_type(::InoRobBusinessGrpc::InfoType_Grpc value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string dt = 2;
inline void PrintInfoItem_Grpc::clear_dt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dt_.ClearToEmpty();
}
inline const std::string& PrintInfoItem_Grpc::dt() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.PrintInfoItem_Grpc.dt)
  return _internal_dt();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PrintInfoItem_Grpc::set_dt(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dt_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.PrintInfoItem_Grpc.dt)
}
inline std::string* PrintInfoItem_Grpc::mutable_dt() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_dt();
  // @@protoc_insertion_point(field_mutable:InoRobBusinessGrpc.PrintInfoItem_Grpc.dt)
  return _s;
}
inline const std::string& PrintInfoItem_Grpc::_internal_dt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dt_.Get();
}
inline void PrintInfoItem_Grpc::_internal_set_dt(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dt_.Set(value, GetArena());
}
inline std::string* PrintInfoItem_Grpc::_internal_mutable_dt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dt_.Mutable( GetArena());
}
inline std::string* PrintInfoItem_Grpc::release_dt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:InoRobBusinessGrpc.PrintInfoItem_Grpc.dt)
  return _impl_.dt_.Release();
}
inline void PrintInfoItem_Grpc::set_allocated_dt(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dt_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.dt_.IsDefault()) {
          _impl_.dt_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:InoRobBusinessGrpc.PrintInfoItem_Grpc.dt)
}

// bytes cont = 3;
inline void PrintInfoItem_Grpc::clear_cont() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cont_.ClearToEmpty();
}
inline const std::string& PrintInfoItem_Grpc::cont() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.PrintInfoItem_Grpc.cont)
  return _internal_cont();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PrintInfoItem_Grpc::set_cont(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cont_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.PrintInfoItem_Grpc.cont)
}
inline std::string* PrintInfoItem_Grpc::mutable_cont() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cont();
  // @@protoc_insertion_point(field_mutable:InoRobBusinessGrpc.PrintInfoItem_Grpc.cont)
  return _s;
}
inline const std::string& PrintInfoItem_Grpc::_internal_cont() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cont_.Get();
}
inline void PrintInfoItem_Grpc::_internal_set_cont(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cont_.Set(value, GetArena());
}
inline std::string* PrintInfoItem_Grpc::_internal_mutable_cont() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cont_.Mutable( GetArena());
}
inline std::string* PrintInfoItem_Grpc::release_cont() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:InoRobBusinessGrpc.PrintInfoItem_Grpc.cont)
  return _impl_.cont_.Release();
}
inline void PrintInfoItem_Grpc::set_allocated_cont(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cont_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.cont_.IsDefault()) {
          _impl_.cont_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:InoRobBusinessGrpc.PrintInfoItem_Grpc.cont)
}

// -------------------------------------------------------------------

// GetPrintInfo_Request

// .InoRobBusinessGrpc.InfoType_Grpc type = 1;
inline void GetPrintInfo_Request::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::InoRobBusinessGrpc::InfoType_Grpc GetPrintInfo_Request::type() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetPrintInfo_Request.type)
  return _internal_type();
}
inline void GetPrintInfo_Request::set_type(::InoRobBusinessGrpc::InfoType_Grpc value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetPrintInfo_Request.type)
}
inline ::InoRobBusinessGrpc::InfoType_Grpc GetPrintInfo_Request::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::InoRobBusinessGrpc::InfoType_Grpc>(_impl_.type_);
}
inline void GetPrintInfo_Request::_internal_set_type(::InoRobBusinessGrpc::InfoType_Grpc value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// uint32 num = 2;
inline void GetPrintInfo_Request::clear_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_ = 0u;
}
inline ::uint32_t GetPrintInfo_Request::num() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetPrintInfo_Request.num)
  return _internal_num();
}
inline void GetPrintInfo_Request::set_num(::uint32_t value) {
  _internal_set_num(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetPrintInfo_Request.num)
}
inline ::uint32_t GetPrintInfo_Request::_internal_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_;
}
inline void GetPrintInfo_Request::_internal_set_num(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_ = value;
}

// -------------------------------------------------------------------

// GetPrintInfo_Response

// repeated .InoRobBusinessGrpc.PrintInfoItem_Grpc printInfoList = 1;
inline int GetPrintInfo_Response::_internal_printinfolist_size() const {
  return _internal_printinfolist().size();
}
inline int GetPrintInfo_Response::printinfolist_size() const {
  return _internal_printinfolist_size();
}
inline void GetPrintInfo_Response::clear_printinfolist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.printinfolist_.Clear();
}
inline ::InoRobBusinessGrpc::PrintInfoItem_Grpc* GetPrintInfo_Response::mutable_printinfolist(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:InoRobBusinessGrpc.GetPrintInfo_Response.printInfoList)
  return _internal_mutable_printinfolist()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>* GetPrintInfo_Response::mutable_printinfolist()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:InoRobBusinessGrpc.GetPrintInfo_Response.printInfoList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_printinfolist();
}
inline const ::InoRobBusinessGrpc::PrintInfoItem_Grpc& GetPrintInfo_Response::printinfolist(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetPrintInfo_Response.printInfoList)
  return _internal_printinfolist().Get(index);
}
inline ::InoRobBusinessGrpc::PrintInfoItem_Grpc* GetPrintInfo_Response::add_printinfolist() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::InoRobBusinessGrpc::PrintInfoItem_Grpc* _add = _internal_mutable_printinfolist()->Add();
  // @@protoc_insertion_point(field_add:InoRobBusinessGrpc.GetPrintInfo_Response.printInfoList)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>& GetPrintInfo_Response::printinfolist() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:InoRobBusinessGrpc.GetPrintInfo_Response.printInfoList)
  return _internal_printinfolist();
}
inline const ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>&
GetPrintInfo_Response::_internal_printinfolist() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.printinfolist_;
}
inline ::google::protobuf::RepeatedPtrField<::InoRobBusinessGrpc::PrintInfoItem_Grpc>*
GetPrintInfo_Response::_internal_mutable_printinfolist() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.printinfolist_;
}

// -------------------------------------------------------------------

// GetWorkstationType_Response

// .InoRobBusinessGrpc.WorkstationType_Grpc workstationType = 1;
inline void GetWorkstationType_Response::clear_workstationtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.workstationtype_ = 0;
}
inline ::InoRobBusinessGrpc::WorkstationType_Grpc GetWorkstationType_Response::workstationtype() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetWorkstationType_Response.workstationType)
  return _internal_workstationtype();
}
inline void GetWorkstationType_Response::set_workstationtype(::InoRobBusinessGrpc::WorkstationType_Grpc value) {
  _internal_set_workstationtype(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetWorkstationType_Response.workstationType)
}
inline ::InoRobBusinessGrpc::WorkstationType_Grpc GetWorkstationType_Response::_internal_workstationtype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::InoRobBusinessGrpc::WorkstationType_Grpc>(_impl_.workstationtype_);
}
inline void GetWorkstationType_Response::_internal_set_workstationtype(::InoRobBusinessGrpc::WorkstationType_Grpc value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.workstationtype_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace InoRobBusinessGrpc


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::InoRobBusinessGrpc::WorkstationType_Grpc> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::InoRobBusinessGrpc::WorkstationType_Grpc>() {
  return ::InoRobBusinessGrpc::WorkstationType_Grpc_descriptor();
}
template <>
struct is_proto_enum<::InoRobBusinessGrpc::InfoType_Grpc> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::InoRobBusinessGrpc::InfoType_Grpc>() {
  return ::InoRobBusinessGrpc::InfoType_Grpc_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_WorkstationGrpc_2eproto_2epb_2eh
