// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WorkstationGrpc.proto
// Protobuf C++ Version: 5.28.1

#include "WorkstationGrpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace InoRobBusinessGrpc {

inline constexpr PrintInfoItem_Grpc::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dt_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cont_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::InoRobBusinessGrpc::InfoType_Grpc >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PrintInfoItem_Grpc::PrintInfoItem_Grpc(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PrintInfoItem_GrpcDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrintInfoItem_GrpcDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrintInfoItem_GrpcDefaultTypeInternal() {}
  union {
    PrintInfoItem_Grpc _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrintInfoItem_GrpcDefaultTypeInternal _PrintInfoItem_Grpc_default_instance_;

inline constexpr GetWorkstationType_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : workstationtype_{static_cast< ::InoRobBusinessGrpc::WorkstationType_Grpc >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetWorkstationType_Response::GetWorkstationType_Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetWorkstationType_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetWorkstationType_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetWorkstationType_ResponseDefaultTypeInternal() {}
  union {
    GetWorkstationType_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetWorkstationType_ResponseDefaultTypeInternal _GetWorkstationType_Response_default_instance_;

inline constexpr GetPrintInfo_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::InoRobBusinessGrpc::InfoType_Grpc >(0)},
        num_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetPrintInfo_Request::GetPrintInfo_Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetPrintInfo_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetPrintInfo_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetPrintInfo_RequestDefaultTypeInternal() {}
  union {
    GetPrintInfo_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetPrintInfo_RequestDefaultTypeInternal _GetPrintInfo_Request_default_instance_;

inline constexpr GetPrintInfo_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : printinfolist_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetPrintInfo_Response::GetPrintInfo_Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetPrintInfo_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetPrintInfo_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetPrintInfo_ResponseDefaultTypeInternal() {}
  union {
    GetPrintInfo_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetPrintInfo_ResponseDefaultTypeInternal _GetPrintInfo_Response_default_instance_;
}  // namespace InoRobBusinessGrpc
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_WorkstationGrpc_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_WorkstationGrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_WorkstationGrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::PrintInfoItem_Grpc, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::PrintInfoItem_Grpc, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::PrintInfoItem_Grpc, _impl_.dt_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::PrintInfoItem_Grpc, _impl_.cont_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetPrintInfo_Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetPrintInfo_Request, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetPrintInfo_Request, _impl_.num_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetPrintInfo_Response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetPrintInfo_Response, _impl_.printinfolist_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetWorkstationType_Response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::GetWorkstationType_Response, _impl_.workstationtype_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::InoRobBusinessGrpc::PrintInfoItem_Grpc)},
        {11, -1, -1, sizeof(::InoRobBusinessGrpc::GetPrintInfo_Request)},
        {21, -1, -1, sizeof(::InoRobBusinessGrpc::GetPrintInfo_Response)},
        {30, -1, -1, sizeof(::InoRobBusinessGrpc::GetWorkstationType_Response)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::InoRobBusinessGrpc::_PrintInfoItem_Grpc_default_instance_._instance,
    &::InoRobBusinessGrpc::_GetPrintInfo_Request_default_instance_._instance,
    &::InoRobBusinessGrpc::_GetPrintInfo_Response_default_instance_._instance,
    &::InoRobBusinessGrpc::_GetWorkstationType_Response_default_instance_._instance,
};
const char descriptor_table_protodef_WorkstationGrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025WorkstationGrpc.proto\022\022InoRobBusinessG"
    "rpc\032\033google/protobuf/empty.proto\032\036google"
    "/protobuf/wrappers.proto\"_\n\022PrintInfoIte"
    "m_Grpc\022/\n\004type\030\001 \001(\0162!.InoRobBusinessGrp"
    "c.InfoType_Grpc\022\n\n\002dt\030\002 \001(\t\022\014\n\004cont\030\003 \001("
    "\014\"T\n\024GetPrintInfo_Request\022/\n\004type\030\001 \001(\0162"
    "!.InoRobBusinessGrpc.InfoType_Grpc\022\013\n\003nu"
    "m\030\002 \001(\r\"V\n\025GetPrintInfo_Response\022=\n\rprin"
    "tInfoList\030\001 \003(\0132&.InoRobBusinessGrpc.Pri"
    "ntInfoItem_Grpc\"`\n\033GetWorkstationType_Re"
    "sponse\022A\n\017workstationType\030\001 \001(\0162(.InoRob"
    "BusinessGrpc.WorkstationType_Grpc*O\n\024Wor"
    "kstationType_Grpc\022\017\n\013Unknow_Grpc\020\000\022\013\n\007TP"
    "_Grpc\020\001\022\013\n\007PC_Grpc\020\002\022\014\n\010TP2_Grpc\020\003*r\n\rIn"
    "foType_Grpc\022\025\n\021MESSAGE_INFO_Grpc\020\000\022\025\n\021WA"
    "RNING_INFO_Grpc\020\001\022\023\n\017ERROR_INFO_Grpc\020\002\022\036"
    "\n\021InfoType_Grpc_All\020\377\377\377\377\377\377\377\377\377\0012\247\003\n\017Works"
    "tationGrpc\022\?\n\005GetID\022\026.google.protobuf.Em"
    "pty\032\034.google.protobuf.StringValue\"\000\022A\n\007G"
    "etName\022\026.google.protobuf.Empty\032\034.google."
    "protobuf.StringValue\"\000\022_\n\022GetWorkstation"
    "Type\022\026.google.protobuf.Empty\032/.InoRobBus"
    "inessGrpc.GetWorkstationType_Response\"\000\022"
    "H\n\016GetAppRootPath\022\026.google.protobuf.Empt"
    "y\032\034.google.protobuf.StringValue\"\000\022e\n\014Get"
    "PrintInfo\022(.InoRobBusinessGrpc.GetPrintI"
    "nfo_Request\032).InoRobBusinessGrpc.GetPrin"
    "tInfo_Response\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_WorkstationGrpc_2eproto_deps[2] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::absl::once_flag descriptor_table_WorkstationGrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_WorkstationGrpc_2eproto = {
    false,
    false,
    1104,
    descriptor_table_protodef_WorkstationGrpc_2eproto,
    "WorkstationGrpc.proto",
    &descriptor_table_WorkstationGrpc_2eproto_once,
    descriptor_table_WorkstationGrpc_2eproto_deps,
    2,
    4,
    schemas,
    file_default_instances,
    TableStruct_WorkstationGrpc_2eproto::offsets,
    file_level_enum_descriptors_WorkstationGrpc_2eproto,
    file_level_service_descriptors_WorkstationGrpc_2eproto,
};
namespace InoRobBusinessGrpc {
const ::google::protobuf::EnumDescriptor* WorkstationType_Grpc_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_WorkstationGrpc_2eproto);
  return file_level_enum_descriptors_WorkstationGrpc_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t WorkstationType_Grpc_internal_data_[] = {
    262144u, 0u, };
bool WorkstationType_Grpc_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* InfoType_Grpc_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_WorkstationGrpc_2eproto);
  return file_level_enum_descriptors_WorkstationGrpc_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t InfoType_Grpc_internal_data_[] = {
    327679u, 0u, };
bool InfoType_Grpc_IsValid(int value) {
  return -1 <= value && value <= 2;
}
// ===================================================================

class PrintInfoItem_Grpc::_Internal {
 public:
};

PrintInfoItem_Grpc::PrintInfoItem_Grpc(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InoRobBusinessGrpc.PrintInfoItem_Grpc)
}
inline PROTOBUF_NDEBUG_INLINE PrintInfoItem_Grpc::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::InoRobBusinessGrpc::PrintInfoItem_Grpc& from_msg)
      : dt_(arena, from.dt_),
        cont_(arena, from.cont_),
        _cached_size_{0} {}

PrintInfoItem_Grpc::PrintInfoItem_Grpc(
    ::google::protobuf::Arena* arena,
    const PrintInfoItem_Grpc& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PrintInfoItem_Grpc* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:InoRobBusinessGrpc.PrintInfoItem_Grpc)
}
inline PROTOBUF_NDEBUG_INLINE PrintInfoItem_Grpc::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : dt_(arena),
        cont_(arena),
        _cached_size_{0} {}

inline void PrintInfoItem_Grpc::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
PrintInfoItem_Grpc::~PrintInfoItem_Grpc() {
  // @@protoc_insertion_point(destructor:InoRobBusinessGrpc.PrintInfoItem_Grpc)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PrintInfoItem_Grpc::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.dt_.Destroy();
  _impl_.cont_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    PrintInfoItem_Grpc::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_PrintInfoItem_Grpc_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &PrintInfoItem_Grpc::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<PrintInfoItem_Grpc>(),
            ::google::protobuf::Message::GetNewImpl<PrintInfoItem_Grpc>(),
            ::google::protobuf::Message::GetClearImpl<PrintInfoItem_Grpc>(), &PrintInfoItem_Grpc::ByteSizeLong,
                &PrintInfoItem_Grpc::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_._cached_size_),
            false,
        },
        &PrintInfoItem_Grpc::kDescriptorMethods,
        &descriptor_table_WorkstationGrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* PrintInfoItem_Grpc::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 48, 2> PrintInfoItem_Grpc::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::PrintInfoItem_Grpc>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrintInfoItem_Grpc, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_.type_)}},
    // string dt = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_.dt_)}},
    // bytes cont = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_.cont_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
    {PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string dt = 2;
    {PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_.dt_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes cont = 3;
    {PROTOBUF_FIELD_OFFSET(PrintInfoItem_Grpc, _impl_.cont_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\0\2\0\0\0\0\0"
    "InoRobBusinessGrpc.PrintInfoItem_Grpc"
    "dt"
  }},
};

PROTOBUF_NOINLINE void PrintInfoItem_Grpc::Clear() {
// @@protoc_insertion_point(message_clear_start:InoRobBusinessGrpc.PrintInfoItem_Grpc)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dt_.ClearToEmpty();
  _impl_.cont_.ClearToEmpty();
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PrintInfoItem_Grpc::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PrintInfoItem_Grpc& this_ = static_cast<const PrintInfoItem_Grpc&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PrintInfoItem_Grpc::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PrintInfoItem_Grpc& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:InoRobBusinessGrpc.PrintInfoItem_Grpc)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // string dt = 2;
          if (!this_._internal_dt().empty()) {
            const std::string& _s = this_._internal_dt();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "InoRobBusinessGrpc.PrintInfoItem_Grpc.dt");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bytes cont = 3;
          if (!this_._internal_cont().empty()) {
            const std::string& _s = this_._internal_cont();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:InoRobBusinessGrpc.PrintInfoItem_Grpc)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PrintInfoItem_Grpc::ByteSizeLong(const MessageLite& base) {
          const PrintInfoItem_Grpc& this_ = static_cast<const PrintInfoItem_Grpc&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PrintInfoItem_Grpc::ByteSizeLong() const {
          const PrintInfoItem_Grpc& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:InoRobBusinessGrpc.PrintInfoItem_Grpc)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string dt = 2;
            if (!this_._internal_dt().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_dt());
            }
            // bytes cont = 3;
            if (!this_._internal_cont().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_cont());
            }
            // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PrintInfoItem_Grpc::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PrintInfoItem_Grpc*>(&to_msg);
  auto& from = static_cast<const PrintInfoItem_Grpc&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:InoRobBusinessGrpc.PrintInfoItem_Grpc)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_dt().empty()) {
    _this->_internal_set_dt(from._internal_dt());
  }
  if (!from._internal_cont().empty()) {
    _this->_internal_set_cont(from._internal_cont());
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PrintInfoItem_Grpc::CopyFrom(const PrintInfoItem_Grpc& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InoRobBusinessGrpc.PrintInfoItem_Grpc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PrintInfoItem_Grpc::InternalSwap(PrintInfoItem_Grpc* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dt_, &other->_impl_.dt_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cont_, &other->_impl_.cont_, arena);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata PrintInfoItem_Grpc::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetPrintInfo_Request::_Internal {
 public:
};

GetPrintInfo_Request::GetPrintInfo_Request(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InoRobBusinessGrpc.GetPrintInfo_Request)
}
GetPrintInfo_Request::GetPrintInfo_Request(
    ::google::protobuf::Arena* arena, const GetPrintInfo_Request& from)
    : GetPrintInfo_Request(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetPrintInfo_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetPrintInfo_Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, num_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::num_));
}
GetPrintInfo_Request::~GetPrintInfo_Request() {
  // @@protoc_insertion_point(destructor:InoRobBusinessGrpc.GetPrintInfo_Request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetPrintInfo_Request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetPrintInfo_Request::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetPrintInfo_Request_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetPrintInfo_Request::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetPrintInfo_Request>(),
            ::google::protobuf::Message::GetNewImpl<GetPrintInfo_Request>(),
            ::google::protobuf::Message::GetClearImpl<GetPrintInfo_Request>(), &GetPrintInfo_Request::ByteSizeLong,
                &GetPrintInfo_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_._cached_size_),
            false,
        },
        &GetPrintInfo_Request::kDescriptorMethods,
        &descriptor_table_WorkstationGrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetPrintInfo_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> GetPrintInfo_Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::GetPrintInfo_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 num = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetPrintInfo_Request, _impl_.num_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_.num_)}},
    // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetPrintInfo_Request, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
    {PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint32 num = 2;
    {PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_.num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetPrintInfo_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:InoRobBusinessGrpc.GetPrintInfo_Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.num_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.num_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetPrintInfo_Request::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetPrintInfo_Request& this_ = static_cast<const GetPrintInfo_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetPrintInfo_Request::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetPrintInfo_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:InoRobBusinessGrpc.GetPrintInfo_Request)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // uint32 num = 2;
          if (this_._internal_num() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_num(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:InoRobBusinessGrpc.GetPrintInfo_Request)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetPrintInfo_Request::ByteSizeLong(const MessageLite& base) {
          const GetPrintInfo_Request& this_ = static_cast<const GetPrintInfo_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetPrintInfo_Request::ByteSizeLong() const {
          const GetPrintInfo_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:InoRobBusinessGrpc.GetPrintInfo_Request)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .InoRobBusinessGrpc.InfoType_Grpc type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // uint32 num = 2;
            if (this_._internal_num() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_num());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetPrintInfo_Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetPrintInfo_Request*>(&to_msg);
  auto& from = static_cast<const GetPrintInfo_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:InoRobBusinessGrpc.GetPrintInfo_Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_num() != 0) {
    _this->_impl_.num_ = from._impl_.num_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetPrintInfo_Request::CopyFrom(const GetPrintInfo_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InoRobBusinessGrpc.GetPrintInfo_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetPrintInfo_Request::InternalSwap(GetPrintInfo_Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_.num_)
      + sizeof(GetPrintInfo_Request::_impl_.num_)
      - PROTOBUF_FIELD_OFFSET(GetPrintInfo_Request, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata GetPrintInfo_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetPrintInfo_Response::_Internal {
 public:
};

GetPrintInfo_Response::GetPrintInfo_Response(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InoRobBusinessGrpc.GetPrintInfo_Response)
}
inline PROTOBUF_NDEBUG_INLINE GetPrintInfo_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::InoRobBusinessGrpc::GetPrintInfo_Response& from_msg)
      : printinfolist_{visibility, arena, from.printinfolist_},
        _cached_size_{0} {}

GetPrintInfo_Response::GetPrintInfo_Response(
    ::google::protobuf::Arena* arena,
    const GetPrintInfo_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetPrintInfo_Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:InoRobBusinessGrpc.GetPrintInfo_Response)
}
inline PROTOBUF_NDEBUG_INLINE GetPrintInfo_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : printinfolist_{visibility, arena},
        _cached_size_{0} {}

inline void GetPrintInfo_Response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetPrintInfo_Response::~GetPrintInfo_Response() {
  // @@protoc_insertion_point(destructor:InoRobBusinessGrpc.GetPrintInfo_Response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetPrintInfo_Response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetPrintInfo_Response::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetPrintInfo_Response_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetPrintInfo_Response::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetPrintInfo_Response>(),
            ::google::protobuf::Message::GetNewImpl<GetPrintInfo_Response>(),
            ::google::protobuf::Message::GetClearImpl<GetPrintInfo_Response>(), &GetPrintInfo_Response::ByteSizeLong,
                &GetPrintInfo_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetPrintInfo_Response, _impl_._cached_size_),
            false,
        },
        &GetPrintInfo_Response::kDescriptorMethods,
        &descriptor_table_WorkstationGrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetPrintInfo_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> GetPrintInfo_Response::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::GetPrintInfo_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .InoRobBusinessGrpc.PrintInfoItem_Grpc printInfoList = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetPrintInfo_Response, _impl_.printinfolist_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .InoRobBusinessGrpc.PrintInfoItem_Grpc printInfoList = 1;
    {PROTOBUF_FIELD_OFFSET(GetPrintInfo_Response, _impl_.printinfolist_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::PrintInfoItem_Grpc>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetPrintInfo_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:InoRobBusinessGrpc.GetPrintInfo_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.printinfolist_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetPrintInfo_Response::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetPrintInfo_Response& this_ = static_cast<const GetPrintInfo_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetPrintInfo_Response::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetPrintInfo_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:InoRobBusinessGrpc.GetPrintInfo_Response)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .InoRobBusinessGrpc.PrintInfoItem_Grpc printInfoList = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_printinfolist_size());
               i < n; i++) {
            const auto& repfield = this_._internal_printinfolist().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:InoRobBusinessGrpc.GetPrintInfo_Response)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetPrintInfo_Response::ByteSizeLong(const MessageLite& base) {
          const GetPrintInfo_Response& this_ = static_cast<const GetPrintInfo_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetPrintInfo_Response::ByteSizeLong() const {
          const GetPrintInfo_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:InoRobBusinessGrpc.GetPrintInfo_Response)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .InoRobBusinessGrpc.PrintInfoItem_Grpc printInfoList = 1;
             {
              total_size += 1UL * this_._internal_printinfolist_size();
              for (const auto& msg : this_._internal_printinfolist()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetPrintInfo_Response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetPrintInfo_Response*>(&to_msg);
  auto& from = static_cast<const GetPrintInfo_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:InoRobBusinessGrpc.GetPrintInfo_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_printinfolist()->MergeFrom(
      from._internal_printinfolist());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetPrintInfo_Response::CopyFrom(const GetPrintInfo_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InoRobBusinessGrpc.GetPrintInfo_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetPrintInfo_Response::InternalSwap(GetPrintInfo_Response* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.printinfolist_.InternalSwap(&other->_impl_.printinfolist_);
}

::google::protobuf::Metadata GetPrintInfo_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetWorkstationType_Response::_Internal {
 public:
};

GetWorkstationType_Response::GetWorkstationType_Response(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InoRobBusinessGrpc.GetWorkstationType_Response)
}
GetWorkstationType_Response::GetWorkstationType_Response(
    ::google::protobuf::Arena* arena, const GetWorkstationType_Response& from)
    : GetWorkstationType_Response(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetWorkstationType_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetWorkstationType_Response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.workstationtype_ = {};
}
GetWorkstationType_Response::~GetWorkstationType_Response() {
  // @@protoc_insertion_point(destructor:InoRobBusinessGrpc.GetWorkstationType_Response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetWorkstationType_Response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetWorkstationType_Response::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetWorkstationType_Response_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetWorkstationType_Response::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetWorkstationType_Response>(),
            ::google::protobuf::Message::GetNewImpl<GetWorkstationType_Response>(),
            ::google::protobuf::Message::GetClearImpl<GetWorkstationType_Response>(), &GetWorkstationType_Response::ByteSizeLong,
                &GetWorkstationType_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetWorkstationType_Response, _impl_._cached_size_),
            false,
        },
        &GetWorkstationType_Response::kDescriptorMethods,
        &descriptor_table_WorkstationGrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetWorkstationType_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetWorkstationType_Response::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::GetWorkstationType_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .InoRobBusinessGrpc.WorkstationType_Grpc workstationType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetWorkstationType_Response, _impl_.workstationtype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetWorkstationType_Response, _impl_.workstationtype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .InoRobBusinessGrpc.WorkstationType_Grpc workstationType = 1;
    {PROTOBUF_FIELD_OFFSET(GetWorkstationType_Response, _impl_.workstationtype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetWorkstationType_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:InoRobBusinessGrpc.GetWorkstationType_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.workstationtype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetWorkstationType_Response::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetWorkstationType_Response& this_ = static_cast<const GetWorkstationType_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetWorkstationType_Response::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetWorkstationType_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:InoRobBusinessGrpc.GetWorkstationType_Response)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .InoRobBusinessGrpc.WorkstationType_Grpc workstationType = 1;
          if (this_._internal_workstationtype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_workstationtype(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:InoRobBusinessGrpc.GetWorkstationType_Response)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetWorkstationType_Response::ByteSizeLong(const MessageLite& base) {
          const GetWorkstationType_Response& this_ = static_cast<const GetWorkstationType_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetWorkstationType_Response::ByteSizeLong() const {
          const GetWorkstationType_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:InoRobBusinessGrpc.GetWorkstationType_Response)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .InoRobBusinessGrpc.WorkstationType_Grpc workstationType = 1;
            if (this_._internal_workstationtype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_workstationtype());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetWorkstationType_Response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetWorkstationType_Response*>(&to_msg);
  auto& from = static_cast<const GetWorkstationType_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:InoRobBusinessGrpc.GetWorkstationType_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_workstationtype() != 0) {
    _this->_impl_.workstationtype_ = from._impl_.workstationtype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetWorkstationType_Response::CopyFrom(const GetWorkstationType_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InoRobBusinessGrpc.GetWorkstationType_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetWorkstationType_Response::InternalSwap(GetWorkstationType_Response* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.workstationtype_, other->_impl_.workstationtype_);
}

::google::protobuf::Metadata GetWorkstationType_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace InoRobBusinessGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_WorkstationGrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
