// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MaintenanceGrpc.proto
#ifndef GRPC_MaintenanceGrpc_2eproto__INCLUDED
#define GRPC_MaintenanceGrpc_2eproto__INCLUDED

#include "MaintenanceGrpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace InoRobBusinessGrpc {

// 维保
class MaintenanceGrpc final {
 public:
  static constexpr char const* service_full_name() {
    return "InoRobBusinessGrpc.MaintenanceGrpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 检查控制器USB是否连接
    // return 连接状态
    virtual ::grpc::Status checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::BoolValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> AsynccheckControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(AsynccheckControllerUSBRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> PrepareAsynccheckControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(PrepareAsynccheckControllerUSBRaw(context, request, cq));
    }
    // 启动诊断
    // return 是否诊断成功（0表示成功）
    virtual ::grpc::Status startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::google::protobuf::Int32Value* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>> AsyncstartDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>>(AsyncstartDiagnoseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>> PrepareAsyncstartDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>>(PrepareAsyncstartDiagnoseRaw(context, request, cq));
    }
    // 停止诊断
    // return 是否停止成功（0表示成功）
    virtual ::grpc::Status stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::google::protobuf::Int32Value* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>> AsyncstopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>>(AsyncstopDiagnoseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>> PrepareAsyncstopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>>(PrepareAsyncstopDiagnoseRaw(context, request, cq));
    }
    // 启动导出报告
    // return 是否成功（0表示成功）
    virtual ::grpc::Status startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::google::protobuf::Int32Value* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>> AsyncstartExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>>(AsyncstartExportReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>> PrepareAsyncstartExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>>(PrepareAsyncstartExportReportRaw(context, request, cq));
    }
    // 获取诊断的保存状态
    virtual ::grpc::Status ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>> AsyncReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>>(AsyncReadErrSaveStaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>> PrepareAsyncReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>>(PrepareAsyncReadErrSaveStaRaw(context, request, cq));
    }
    // 获取诊断报告的导出状态
    virtual ::grpc::Status ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>> AsyncReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>>(AsyncReadErrExportStaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>> PrepareAsyncReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>>(PrepareAsyncReadErrExportStaRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 检查控制器USB是否连接
      // return 连接状态
      virtual void checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) = 0;
      virtual void checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 启动诊断
      // return 是否诊断成功（0表示成功）
      virtual void startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)>) = 0;
      virtual void startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 停止诊断
      // return 是否停止成功（0表示成功）
      virtual void stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)>) = 0;
      virtual void stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 启动导出报告
      // return 是否成功（0表示成功）
      virtual void startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)>) = 0;
      virtual void startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取诊断的保存状态
      virtual void ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取诊断报告的导出状态
      virtual void ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* AsynccheckControllerUSBRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* PrepareAsynccheckControllerUSBRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>* AsyncstartDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>* PrepareAsyncstartDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>* AsyncstopDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>* PrepareAsyncstopDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>* AsyncstartExportReportRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Int32Value>* PrepareAsyncstartExportReportRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* AsyncReadErrSaveStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* PrepareAsyncReadErrSaveStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* AsyncReadErrExportStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* PrepareAsyncReadErrExportStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::BoolValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> AsynccheckControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(AsynccheckControllerUSBRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> PrepareAsynccheckControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(PrepareAsynccheckControllerUSBRaw(context, request, cq));
    }
    ::grpc::Status startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::google::protobuf::Int32Value* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>> AsyncstartDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>>(AsyncstartDiagnoseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>> PrepareAsyncstartDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>>(PrepareAsyncstartDiagnoseRaw(context, request, cq));
    }
    ::grpc::Status stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::google::protobuf::Int32Value* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>> AsyncstopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>>(AsyncstopDiagnoseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>> PrepareAsyncstopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>>(PrepareAsyncstopDiagnoseRaw(context, request, cq));
    }
    ::grpc::Status startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::google::protobuf::Int32Value* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>> AsyncstartExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>>(AsyncstartExportReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>> PrepareAsyncstartExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>>(PrepareAsyncstartExportReportRaw(context, request, cq));
    }
    ::grpc::Status ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>> AsyncReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>>(AsyncReadErrSaveStaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>> PrepareAsyncReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>>(PrepareAsyncReadErrSaveStaRaw(context, request, cq));
    }
    ::grpc::Status ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>> AsyncReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>>(AsyncReadErrExportStaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>> PrepareAsyncReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>>(PrepareAsyncReadErrExportStaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) override;
      void checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) override;
      void startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)>) override;
      void startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) override;
      void stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)>) override;
      void stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) override;
      void startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)>) override;
      void startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response, std::function<void(::grpc::Status)>) override;
      void ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response, std::function<void(::grpc::Status)>) override;
      void ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* AsynccheckControllerUSBRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* PrepareAsynccheckControllerUSBRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* AsyncstartDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* PrepareAsyncstartDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* AsyncstopDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* PrepareAsyncstopDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* AsyncstartExportReportRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* PrepareAsyncstartExportReportRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* AsyncReadErrSaveStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* PrepareAsyncReadErrSaveStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* AsyncReadErrExportStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* PrepareAsyncReadErrExportStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_checkControllerUSB_;
    const ::grpc::internal::RpcMethod rpcmethod_startDiagnose_;
    const ::grpc::internal::RpcMethod rpcmethod_stopDiagnose_;
    const ::grpc::internal::RpcMethod rpcmethod_startExportReport_;
    const ::grpc::internal::RpcMethod rpcmethod_ReadErrSaveSta_;
    const ::grpc::internal::RpcMethod rpcmethod_ReadErrExportSta_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 检查控制器USB是否连接
    // return 连接状态
    virtual ::grpc::Status checkControllerUSB(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response);
    // 启动诊断
    // return 是否诊断成功（0表示成功）
    virtual ::grpc::Status startDiagnose(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response);
    // 停止诊断
    // return 是否停止成功（0表示成功）
    virtual ::grpc::Status stopDiagnose(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response);
    // 启动导出报告
    // return 是否成功（0表示成功）
    virtual ::grpc::Status startExportReport(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response);
    // 获取诊断的保存状态
    virtual ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response);
    // 获取诊断报告的导出状态
    virtual ::grpc::Status ReadErrExportSta(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_checkControllerUSB : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_checkControllerUSB() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_checkControllerUSB() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkControllerUSB(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcheckControllerUSB(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::BoolValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_startDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_startDiagnose() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_startDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststartDiagnose(::grpc::ServerContext* context, ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Int32Value>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_stopDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_stopDiagnose() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_stopDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stopDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststopDiagnose(::grpc::ServerContext* context, ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Int32Value>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_startExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_startExportReport() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_startExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startExportReport(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststartExportReport(::grpc::ServerContext* context, ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Int32Value>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadErrSaveSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadErrSaveSta() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_ReadErrSaveSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadErrSaveSta(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadErrExportSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadErrExportSta() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ReadErrExportSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrExportSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadErrExportSta(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_checkControllerUSB<WithAsyncMethod_startDiagnose<WithAsyncMethod_stopDiagnose<WithAsyncMethod_startExportReport<WithAsyncMethod_ReadErrSaveSta<WithAsyncMethod_ReadErrExportSta<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_checkControllerUSB : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_checkControllerUSB() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::google::protobuf::BoolValue>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response) { return this->checkControllerUSB(context, request, response); }));}
    void SetMessageAllocatorFor_checkControllerUSB(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::google::protobuf::BoolValue>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::google::protobuf::BoolValue>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_checkControllerUSB() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkControllerUSB(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* checkControllerUSB(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_startDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_startDiagnose() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response) { return this->startDiagnose(context, request, response); }));}
    void SetMessageAllocatorFor_startDiagnose(
        ::grpc::MessageAllocator< ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_startDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* startDiagnose(
      ::grpc::CallbackServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_stopDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_stopDiagnose() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response) { return this->stopDiagnose(context, request, response); }));}
    void SetMessageAllocatorFor_stopDiagnose(
        ::grpc::MessageAllocator< ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_stopDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stopDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* stopDiagnose(
      ::grpc::CallbackServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_startExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_startExportReport() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response) { return this->startExportReport(context, request, response); }));}
    void SetMessageAllocatorFor_startExportReport(
        ::grpc::MessageAllocator< ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_startExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startExportReport(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* startExportReport(
      ::grpc::CallbackServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReadErrSaveSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadErrSaveSta() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response) { return this->ReadErrSaveSta(context, request, response); }));}
    void SetMessageAllocatorFor_ReadErrSaveSta(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadErrSaveSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadErrSaveSta(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReadErrExportSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadErrExportSta() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response) { return this->ReadErrExportSta(context, request, response); }));}
    void SetMessageAllocatorFor_ReadErrExportSta(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadErrExportSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrExportSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadErrExportSta(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_checkControllerUSB<WithCallbackMethod_startDiagnose<WithCallbackMethod_stopDiagnose<WithCallbackMethod_startExportReport<WithCallbackMethod_ReadErrSaveSta<WithCallbackMethod_ReadErrExportSta<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_checkControllerUSB : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_checkControllerUSB() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_checkControllerUSB() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkControllerUSB(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_startDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_startDiagnose() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_startDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_stopDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_stopDiagnose() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_stopDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stopDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_startExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_startExportReport() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_startExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startExportReport(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReadErrSaveSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadErrSaveSta() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_ReadErrSaveSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReadErrExportSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadErrExportSta() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ReadErrExportSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrExportSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_checkControllerUSB : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_checkControllerUSB() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_checkControllerUSB() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkControllerUSB(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcheckControllerUSB(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_startDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_startDiagnose() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_startDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststartDiagnose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_stopDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_stopDiagnose() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_stopDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stopDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststopDiagnose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_startExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_startExportReport() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_startExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startExportReport(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequeststartExportReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadErrSaveSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadErrSaveSta() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_ReadErrSaveSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadErrSaveSta(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadErrExportSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadErrExportSta() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ReadErrExportSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrExportSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadErrExportSta(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_checkControllerUSB : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_checkControllerUSB() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->checkControllerUSB(context, request, response); }));
    }
    ~WithRawCallbackMethod_checkControllerUSB() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkControllerUSB(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* checkControllerUSB(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_startDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_startDiagnose() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->startDiagnose(context, request, response); }));
    }
    ~WithRawCallbackMethod_startDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* startDiagnose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_stopDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_stopDiagnose() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->stopDiagnose(context, request, response); }));
    }
    ~WithRawCallbackMethod_stopDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stopDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* stopDiagnose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_startExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_startExportReport() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->startExportReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_startExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status startExportReport(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* startExportReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadErrSaveSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadErrSaveSta() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadErrSaveSta(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadErrSaveSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadErrSaveSta(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadErrExportSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadErrExportSta() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadErrExportSta(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadErrExportSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadErrExportSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadErrExportSta(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_checkControllerUSB : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_checkControllerUSB() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::google::protobuf::BoolValue>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::google::protobuf::BoolValue>* streamer) {
                       return this->StreamedcheckControllerUSB(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_checkControllerUSB() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status checkControllerUSB(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcheckControllerUSB(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::google::protobuf::BoolValue>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_startDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_startDiagnose() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value>* streamer) {
                       return this->StreamedstartDiagnose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_startDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status startDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedstartDiagnose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request,::google::protobuf::Int32Value>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_stopDiagnose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_stopDiagnose() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value>* streamer) {
                       return this->StreamedstopDiagnose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_stopDiagnose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status stopDiagnose(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedstopDiagnose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request,::google::protobuf::Int32Value>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_startExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_startExportReport() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value>* streamer) {
                       return this->StreamedstartExportReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_startExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status startExportReport(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* /*request*/, ::google::protobuf::Int32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedstartExportReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request,::google::protobuf::Int32Value>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadErrSaveSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadErrSaveSta() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* streamer) {
                       return this->StreamedReadErrSaveSta(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadErrSaveSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadErrSaveSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadErrSaveSta(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadErrExportSta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadErrExportSta() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* streamer) {
                       return this->StreamedReadErrExportSta(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadErrExportSta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadErrExportSta(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadErrExportSta(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_checkControllerUSB<WithStreamedUnaryMethod_startDiagnose<WithStreamedUnaryMethod_stopDiagnose<WithStreamedUnaryMethod_startExportReport<WithStreamedUnaryMethod_ReadErrSaveSta<WithStreamedUnaryMethod_ReadErrExportSta<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_checkControllerUSB<WithStreamedUnaryMethod_startDiagnose<WithStreamedUnaryMethod_stopDiagnose<WithStreamedUnaryMethod_startExportReport<WithStreamedUnaryMethod_ReadErrSaveSta<WithStreamedUnaryMethod_ReadErrExportSta<Service > > > > > > StreamedService;
};

}  // namespace InoRobBusinessGrpc


#endif  // GRPC_MaintenanceGrpc_2eproto__INCLUDED
