// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MaintenanceGrpc.proto

#include "MaintenanceGrpc.pb.h"
#include "MaintenanceGrpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace InoRobBusinessGrpc {

static const char* MaintenanceGrpc_method_names[] = {
  "/InoRobBusinessGrpc.MaintenanceGrpc/checkControllerUSB",
  "/InoRobBusinessGrpc.MaintenanceGrpc/startDiagnose",
  "/InoRobBusinessGrpc.MaintenanceGrpc/stopDiagnose",
  "/InoRobBusinessGrpc.MaintenanceGrpc/startExportReport",
  "/InoRobBusinessGrpc.MaintenanceGrpc/ReadErrSaveSta",
  "/InoRobBusinessGrpc.MaintenanceGrpc/ReadErrExportSta",
};

std::unique_ptr< MaintenanceGrpc::Stub> MaintenanceGrpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MaintenanceGrpc::Stub> stub(new MaintenanceGrpc::Stub(channel, options));
  return stub;
}

MaintenanceGrpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_checkControllerUSB_(MaintenanceGrpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_startDiagnose_(MaintenanceGrpc_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_stopDiagnose_(MaintenanceGrpc_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_startExportReport_(MaintenanceGrpc_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadErrSaveSta_(MaintenanceGrpc_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadErrExportSta_(MaintenanceGrpc_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MaintenanceGrpc::Stub::checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::BoolValue* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_checkControllerUSB_, context, request, response);
}

void MaintenanceGrpc::Stub::async::checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_checkControllerUSB_, context, request, response, std::move(f));
}

void MaintenanceGrpc::Stub::async::checkControllerUSB(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_checkControllerUSB_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* MaintenanceGrpc::Stub::PrepareAsynccheckControllerUSBRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::BoolValue, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_checkControllerUSB_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* MaintenanceGrpc::Stub::AsynccheckControllerUSBRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccheckControllerUSBRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MaintenanceGrpc::Stub::startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::google::protobuf::Int32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_startDiagnose_, context, request, response);
}

void MaintenanceGrpc::Stub::async::startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_startDiagnose_, context, request, response, std::move(f));
}

void MaintenanceGrpc::Stub::async::startDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_startDiagnose_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* MaintenanceGrpc::Stub::PrepareAsyncstartDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Int32Value, ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_startDiagnose_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* MaintenanceGrpc::Stub::AsyncstartDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncstartDiagnoseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MaintenanceGrpc::Stub::stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::google::protobuf::Int32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_stopDiagnose_, context, request, response);
}

void MaintenanceGrpc::Stub::async::stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_stopDiagnose_, context, request, response, std::move(f));
}

void MaintenanceGrpc::Stub::async::stopDiagnose(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_stopDiagnose_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* MaintenanceGrpc::Stub::PrepareAsyncstopDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Int32Value, ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_stopDiagnose_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* MaintenanceGrpc::Stub::AsyncstopDiagnoseRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncstopDiagnoseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MaintenanceGrpc::Stub::startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::google::protobuf::Int32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_startExportReport_, context, request, response);
}

void MaintenanceGrpc::Stub::async::startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_startExportReport_, context, request, response, std::move(f));
}

void MaintenanceGrpc::Stub::async::startExportReport(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_startExportReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* MaintenanceGrpc::Stub::PrepareAsyncstartExportReportRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Int32Value, ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_startExportReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* MaintenanceGrpc::Stub::AsyncstartExportReportRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncstartExportReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MaintenanceGrpc::Stub::ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadErrSaveSta_, context, request, response);
}

void MaintenanceGrpc::Stub::async::ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadErrSaveSta_, context, request, response, std::move(f));
}

void MaintenanceGrpc::Stub::async::ReadErrSaveSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadErrSaveSta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* MaintenanceGrpc::Stub::PrepareAsyncReadErrSaveStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadErrSaveSta_, context, request);
}

::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response>* MaintenanceGrpc::Stub::AsyncReadErrSaveStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadErrSaveStaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MaintenanceGrpc::Stub::ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadErrExportSta_, context, request, response);
}

void MaintenanceGrpc::Stub::async::ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadErrExportSta_, context, request, response, std::move(f));
}

void MaintenanceGrpc::Stub::async::ReadErrExportSta(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadErrExportSta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* MaintenanceGrpc::Stub::PrepareAsyncReadErrExportStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadErrExportSta_, context, request);
}

::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response>* MaintenanceGrpc::Stub::AsyncReadErrExportStaRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadErrExportStaRaw(context, request, cq);
  result->StartCall();
  return result;
}

MaintenanceGrpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MaintenanceGrpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MaintenanceGrpc::Service, ::google::protobuf::Empty, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MaintenanceGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::BoolValue* resp) {
               return service->checkControllerUSB(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MaintenanceGrpc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MaintenanceGrpc::Service, ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MaintenanceGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* req,
             ::google::protobuf::Int32Value* resp) {
               return service->startDiagnose(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MaintenanceGrpc_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MaintenanceGrpc::Service, ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MaintenanceGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* req,
             ::google::protobuf::Int32Value* resp) {
               return service->stopDiagnose(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MaintenanceGrpc_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MaintenanceGrpc::Service, ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MaintenanceGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* req,
             ::google::protobuf::Int32Value* resp) {
               return service->startExportReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MaintenanceGrpc_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MaintenanceGrpc::Service, ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MaintenanceGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* resp) {
               return service->ReadErrSaveSta(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MaintenanceGrpc_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MaintenanceGrpc::Service, ::google::protobuf::Empty, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MaintenanceGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* resp) {
               return service->ReadErrExportSta(ctx, req, resp);
             }, this)));
}

MaintenanceGrpc::Service::~Service() {
}

::grpc::Status MaintenanceGrpc::Service::checkControllerUSB(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::BoolValue* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MaintenanceGrpc::Service::startDiagnose(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startDiagnose_Request* request, ::google::protobuf::Int32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MaintenanceGrpc::Service::stopDiagnose(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_stopDiagnose_Request* request, ::google::protobuf::Int32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MaintenanceGrpc::Service::startExportReport(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::MaintenanceGrpc_startExportReport_Request* request, ::google::protobuf::Int32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MaintenanceGrpc::Service::ReadErrSaveSta(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrSaveSta_Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MaintenanceGrpc::Service::ReadErrExportSta(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::MaintenanceGrpc_ReadErrExportSta_Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace InoRobBusinessGrpc

