// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ConnectionGrpc.proto

#include "ConnectionGrpc.pb.h"
#include "ConnectionGrpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace InoRobBusinessGrpc {

static const char* ConnectionGrpc_method_names[] = {
  "/InoRobBusinessGrpc.ConnectionGrpc/GetIp",
  "/InoRobBusinessGrpc.ConnectionGrpc/SetIp",
  "/InoRobBusinessGrpc.ConnectionGrpc/GetPort",
  "/InoRobBusinessGrpc.ConnectionGrpc/setPort",
  "/InoRobBusinessGrpc.ConnectionGrpc/GetConnectionStatus",
  "/InoRobBusinessGrpc.ConnectionGrpc/Connect",
  "/InoRobBusinessGrpc.ConnectionGrpc/Close",
  "/InoRobBusinessGrpc.ConnectionGrpc/connectionStatusChanged",
  "/InoRobBusinessGrpc.ConnectionGrpc/skipBootConnect",
};

std::unique_ptr< ConnectionGrpc::Stub> ConnectionGrpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ConnectionGrpc::Stub> stub(new ConnectionGrpc::Stub(channel, options));
  return stub;
}

ConnectionGrpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetIp_(ConnectionGrpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetIp_(ConnectionGrpc_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPort_(ConnectionGrpc_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setPort_(ConnectionGrpc_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetConnectionStatus_(ConnectionGrpc_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Connect_(ConnectionGrpc_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Close_(ConnectionGrpc_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_connectionStatusChanged_(ConnectionGrpc_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_skipBootConnect_(ConnectionGrpc_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ConnectionGrpc::Stub::GetIp(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::StringValue* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::StringValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetIp_, context, request, response);
}

void ConnectionGrpc::Stub::async::GetIp(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::StringValue* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::StringValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetIp_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::GetIp(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::StringValue* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetIp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::StringValue>* ConnectionGrpc::Stub::PrepareAsyncGetIpRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::StringValue, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetIp_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::StringValue>* ConnectionGrpc::Stub::AsyncGetIpRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetIpRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionGrpc::Stub::SetIp(::grpc::ClientContext* context, const ::google::protobuf::StringValue& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::StringValue, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetIp_, context, request, response);
}

void ConnectionGrpc::Stub::async::SetIp(::grpc::ClientContext* context, const ::google::protobuf::StringValue* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::StringValue, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetIp_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::SetIp(::grpc::ClientContext* context, const ::google::protobuf::StringValue* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetIp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ConnectionGrpc::Stub::PrepareAsyncSetIpRaw(::grpc::ClientContext* context, const ::google::protobuf::StringValue& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::google::protobuf::StringValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetIp_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ConnectionGrpc::Stub::AsyncSetIpRaw(::grpc::ClientContext* context, const ::google::protobuf::StringValue& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetIpRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionGrpc::Stub::GetPort(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPort_, context, request, response);
}

void ConnectionGrpc::Stub::async::GetPort(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPort_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::GetPort(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPort_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* ConnectionGrpc::Stub::PrepareAsyncGetPortRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPort_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* ConnectionGrpc::Stub::AsyncGetPortRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPortRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionGrpc::Stub::setPort(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::UInt32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setPort_, context, request, response);
}

void ConnectionGrpc::Stub::async::setPort(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::UInt32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setPort_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::setPort(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setPort_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ConnectionGrpc::Stub::PrepareAsyncsetPortRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setPort_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ConnectionGrpc::Stub::AsyncsetPortRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetPortRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionGrpc::Stub::GetConnectionStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::GetConnectionStatus_Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::InoRobBusinessGrpc::GetConnectionStatus_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetConnectionStatus_, context, request, response);
}

void ConnectionGrpc::Stub::async::GetConnectionStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::GetConnectionStatus_Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::InoRobBusinessGrpc::GetConnectionStatus_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConnectionStatus_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::GetConnectionStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::GetConnectionStatus_Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConnectionStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* ConnectionGrpc::Stub::PrepareAsyncGetConnectionStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::InoRobBusinessGrpc::GetConnectionStatus_Response, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetConnectionStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* ConnectionGrpc::Stub::AsyncGetConnectionStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetConnectionStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionGrpc::Stub::Connect(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::GetConnectionStatus_Request& request, ::google::protobuf::BoolValue* response) {
  return ::grpc::internal::BlockingUnaryCall< ::InoRobBusinessGrpc::GetConnectionStatus_Request, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Connect_, context, request, response);
}

void ConnectionGrpc::Stub::async::Connect(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::GetConnectionStatus_Request* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::InoRobBusinessGrpc::GetConnectionStatus_Request, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::Connect(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::GetConnectionStatus_Request* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* ConnectionGrpc::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::GetConnectionStatus_Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::BoolValue, ::InoRobBusinessGrpc::GetConnectionStatus_Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Connect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* ConnectionGrpc::Stub::AsyncConnectRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::GetConnectionStatus_Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionGrpc::Stub::Close(::grpc::ClientContext* context, const ::google::protobuf::BoolValue& request, ::google::protobuf::BoolValue* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::BoolValue, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Close_, context, request, response);
}

void ConnectionGrpc::Stub::async::Close(::grpc::ClientContext* context, const ::google::protobuf::BoolValue* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::BoolValue, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Close_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::Close(::grpc::ClientContext* context, const ::google::protobuf::BoolValue* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Close_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* ConnectionGrpc::Stub::PrepareAsyncCloseRaw(::grpc::ClientContext* context, const ::google::protobuf::BoolValue& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::BoolValue, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Close_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* ConnectionGrpc::Stub::AsyncCloseRaw(::grpc::ClientContext* context, const ::google::protobuf::BoolValue& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* ConnectionGrpc::Stub::connectionStatusChangedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::InoRobBusinessGrpc::GetConnectionStatus_Response>::Create(channel_.get(), rpcmethod_connectionStatusChanged_, context, request);
}

void ConnectionGrpc::Stub::async::connectionStatusChanged(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::InoRobBusinessGrpc::GetConnectionStatus_Response>::Create(stub_->channel_.get(), stub_->rpcmethod_connectionStatusChanged_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* ConnectionGrpc::Stub::AsyncconnectionStatusChangedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::InoRobBusinessGrpc::GetConnectionStatus_Response>::Create(channel_.get(), cq, rpcmethod_connectionStatusChanged_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* ConnectionGrpc::Stub::PrepareAsyncconnectionStatusChangedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::InoRobBusinessGrpc::GetConnectionStatus_Response>::Create(channel_.get(), cq, rpcmethod_connectionStatusChanged_, context, request, false, nullptr);
}

::grpc::Status ConnectionGrpc::Stub::skipBootConnect(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::Int32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_skipBootConnect_, context, request, response);
}

void ConnectionGrpc::Stub::async::skipBootConnect(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Int32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_skipBootConnect_, context, request, response, std::move(f));
}

void ConnectionGrpc::Stub::async::skipBootConnect(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Int32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_skipBootConnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* ConnectionGrpc::Stub::PrepareAsyncskipBootConnectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Int32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_skipBootConnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Int32Value>* ConnectionGrpc::Stub::AsyncskipBootConnectRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncskipBootConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

ConnectionGrpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::Empty, ::google::protobuf::StringValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::StringValue* resp) {
               return service->GetIp(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::StringValue, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::StringValue* req,
             ::google::protobuf::Empty* resp) {
               return service->SetIp(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->GetPort(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::UInt32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::UInt32Value* req,
             ::google::protobuf::Empty* resp) {
               return service->setPort(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::Empty, ::InoRobBusinessGrpc::GetConnectionStatus_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::InoRobBusinessGrpc::GetConnectionStatus_Response* resp) {
               return service->GetConnectionStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::InoRobBusinessGrpc::GetConnectionStatus_Request, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::InoRobBusinessGrpc::GetConnectionStatus_Request* req,
             ::google::protobuf::BoolValue* resp) {
               return service->Connect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::BoolValue, ::google::protobuf::BoolValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::BoolValue* req,
             ::google::protobuf::BoolValue* resp) {
               return service->Close(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[7],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ConnectionGrpc::Service, ::google::protobuf::Empty, ::InoRobBusinessGrpc::GetConnectionStatus_Response>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::InoRobBusinessGrpc::GetConnectionStatus_Response>* writer) {
               return service->connectionStatusChanged(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionGrpc_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionGrpc::Service, ::google::protobuf::Empty, ::google::protobuf::Int32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::Int32Value* resp) {
               return service->skipBootConnect(ctx, req, resp);
             }, this)));
}

ConnectionGrpc::Service::~Service() {
}

::grpc::Status ConnectionGrpc::Service::GetIp(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::StringValue* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::SetIp(::grpc::ServerContext* context, const ::google::protobuf::StringValue* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::GetPort(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::setPort(::grpc::ServerContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::GetConnectionStatus(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::GetConnectionStatus_Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::Connect(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::GetConnectionStatus_Request* request, ::google::protobuf::BoolValue* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::Close(::grpc::ServerContext* context, const ::google::protobuf::BoolValue* request, ::google::protobuf::BoolValue* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::connectionStatusChanged(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::InoRobBusinessGrpc::GetConnectionStatus_Response>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionGrpc::Service::skipBootConnect(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Int32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace InoRobBusinessGrpc

