// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ConnectionGrpc.proto
// Protobuf C++ Version: 5.28.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_ConnectionGrpc_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ConnectionGrpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/wrappers.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ConnectionGrpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ConnectionGrpc_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ConnectionGrpc_2eproto;
namespace InoRobBusinessGrpc {
class GetConnectionStatus_Request;
struct GetConnectionStatus_RequestDefaultTypeInternal;
extern GetConnectionStatus_RequestDefaultTypeInternal _GetConnectionStatus_Request_default_instance_;
class GetConnectionStatus_Response;
struct GetConnectionStatus_ResponseDefaultTypeInternal;
extern GetConnectionStatus_ResponseDefaultTypeInternal _GetConnectionStatus_Response_default_instance_;
}  // namespace InoRobBusinessGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace InoRobBusinessGrpc {
enum ControllerConnectionStatus_Grpc : int {
  CONTROLLER_CONNECTION_STATUS_CLOSED_Grpc = 0,
  CONTROLLER_CONNECTION_STATUS_CONNECTING_Grpc = 1,
  CONTROLLER_CONNECTION_STATUS_CONNECTED_Grpc = 2,
  ControllerConnectionStatus_Grpc_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ControllerConnectionStatus_Grpc_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ControllerConnectionStatus_Grpc_IsValid(int value);
extern const uint32_t ControllerConnectionStatus_Grpc_internal_data_[];
constexpr ControllerConnectionStatus_Grpc ControllerConnectionStatus_Grpc_MIN = static_cast<ControllerConnectionStatus_Grpc>(0);
constexpr ControllerConnectionStatus_Grpc ControllerConnectionStatus_Grpc_MAX = static_cast<ControllerConnectionStatus_Grpc>(2);
constexpr int ControllerConnectionStatus_Grpc_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ControllerConnectionStatus_Grpc_descriptor();
template <typename T>
const std::string& ControllerConnectionStatus_Grpc_Name(T value) {
  static_assert(std::is_same<T, ControllerConnectionStatus_Grpc>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ControllerConnectionStatus_Grpc_Name().");
  return ControllerConnectionStatus_Grpc_Name(static_cast<ControllerConnectionStatus_Grpc>(value));
}
template <>
inline const std::string& ControllerConnectionStatus_Grpc_Name(ControllerConnectionStatus_Grpc value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ControllerConnectionStatus_Grpc_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ControllerConnectionStatus_Grpc_Parse(absl::string_view name, ControllerConnectionStatus_Grpc* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ControllerConnectionStatus_Grpc>(
      ControllerConnectionStatus_Grpc_descriptor(), name, value);
}
enum ConnentType_Grpc : int {
  CONNECT_DEFAULT_TYPE_Grpc = 0,
  CONNECT_PC_TYPE_Grpc = 1,
  CONNECT_TP_TYPE_Grpc = 2,
  CONNECT_HAND_TP_TYPE_Grpc = 3,
  ConnentType_Grpc_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ConnentType_Grpc_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ConnentType_Grpc_IsValid(int value);
extern const uint32_t ConnentType_Grpc_internal_data_[];
constexpr ConnentType_Grpc ConnentType_Grpc_MIN = static_cast<ConnentType_Grpc>(0);
constexpr ConnentType_Grpc ConnentType_Grpc_MAX = static_cast<ConnentType_Grpc>(3);
constexpr int ConnentType_Grpc_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
ConnentType_Grpc_descriptor();
template <typename T>
const std::string& ConnentType_Grpc_Name(T value) {
  static_assert(std::is_same<T, ConnentType_Grpc>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ConnentType_Grpc_Name().");
  return ConnentType_Grpc_Name(static_cast<ConnentType_Grpc>(value));
}
template <>
inline const std::string& ConnentType_Grpc_Name(ConnentType_Grpc value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ConnentType_Grpc_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool ConnentType_Grpc_Parse(absl::string_view name, ConnentType_Grpc* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConnentType_Grpc>(
      ConnentType_Grpc_descriptor(), name, value);
}
enum ConnectVersion_Grpc : int {
  CONNECT_DEFAULT_VER_Grpc = 0,
  CONNECT_TP_1_0_Grpc = 256,
  CONNECT_TP_2_0_Grpc = 512,
  ConnectVersion_Grpc_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ConnectVersion_Grpc_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ConnectVersion_Grpc_IsValid(int value);
extern const uint32_t ConnectVersion_Grpc_internal_data_[];
constexpr ConnectVersion_Grpc ConnectVersion_Grpc_MIN = static_cast<ConnectVersion_Grpc>(0);
constexpr ConnectVersion_Grpc ConnectVersion_Grpc_MAX = static_cast<ConnectVersion_Grpc>(512);
constexpr int ConnectVersion_Grpc_ARRAYSIZE = 512 + 1;
const ::google::protobuf::EnumDescriptor*
ConnectVersion_Grpc_descriptor();
template <typename T>
const std::string& ConnectVersion_Grpc_Name(T value) {
  static_assert(std::is_same<T, ConnectVersion_Grpc>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ConnectVersion_Grpc_Name().");
  return ::google::protobuf::internal::NameOfEnum(ConnectVersion_Grpc_descriptor(), value);
}
inline bool ConnectVersion_Grpc_Parse(absl::string_view name, ConnectVersion_Grpc* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConnectVersion_Grpc>(
      ConnectVersion_Grpc_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class GetConnectionStatus_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.GetConnectionStatus_Response) */ {
 public:
  inline GetConnectionStatus_Response() : GetConnectionStatus_Response(nullptr) {}
  ~GetConnectionStatus_Response() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetConnectionStatus_Response(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetConnectionStatus_Response(const GetConnectionStatus_Response& from) : GetConnectionStatus_Response(nullptr, from) {}
  inline GetConnectionStatus_Response(GetConnectionStatus_Response&& from) noexcept
      : GetConnectionStatus_Response(nullptr, std::move(from)) {}
  inline GetConnectionStatus_Response& operator=(const GetConnectionStatus_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetConnectionStatus_Response& operator=(GetConnectionStatus_Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetConnectionStatus_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetConnectionStatus_Response* internal_default_instance() {
    return reinterpret_cast<const GetConnectionStatus_Response*>(
        &_GetConnectionStatus_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GetConnectionStatus_Response& a, GetConnectionStatus_Response& b) { a.Swap(&b); }
  inline void Swap(GetConnectionStatus_Response* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetConnectionStatus_Response* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetConnectionStatus_Response* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetConnectionStatus_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetConnectionStatus_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetConnectionStatus_Response& from) { GetConnectionStatus_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetConnectionStatus_Response* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.GetConnectionStatus_Response"; }

 protected:
  explicit GetConnectionStatus_Response(::google::protobuf::Arena* arena);
  GetConnectionStatus_Response(::google::protobuf::Arena* arena, const GetConnectionStatus_Response& from);
  GetConnectionStatus_Response(::google::protobuf::Arena* arena, GetConnectionStatus_Response&& from) noexcept
      : GetConnectionStatus_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kControllerConnectionStatusFieldNumber = 1,
  };
  // .InoRobBusinessGrpc.ControllerConnectionStatus_Grpc controllerConnectionStatus = 1;
  void clear_controllerconnectionstatus() ;
  ::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc controllerconnectionstatus() const;
  void set_controllerconnectionstatus(::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc value);

  private:
  ::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc _internal_controllerconnectionstatus() const;
  void _internal_set_controllerconnectionstatus(::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.GetConnectionStatus_Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetConnectionStatus_Response_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetConnectionStatus_Response& from_msg);
    int controllerconnectionstatus_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ConnectionGrpc_2eproto;
};
// -------------------------------------------------------------------

class GetConnectionStatus_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.GetConnectionStatus_Request) */ {
 public:
  inline GetConnectionStatus_Request() : GetConnectionStatus_Request(nullptr) {}
  ~GetConnectionStatus_Request() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetConnectionStatus_Request(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetConnectionStatus_Request(const GetConnectionStatus_Request& from) : GetConnectionStatus_Request(nullptr, from) {}
  inline GetConnectionStatus_Request(GetConnectionStatus_Request&& from) noexcept
      : GetConnectionStatus_Request(nullptr, std::move(from)) {}
  inline GetConnectionStatus_Request& operator=(const GetConnectionStatus_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetConnectionStatus_Request& operator=(GetConnectionStatus_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetConnectionStatus_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetConnectionStatus_Request* internal_default_instance() {
    return reinterpret_cast<const GetConnectionStatus_Request*>(
        &_GetConnectionStatus_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GetConnectionStatus_Request& a, GetConnectionStatus_Request& b) { a.Swap(&b); }
  inline void Swap(GetConnectionStatus_Request* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetConnectionStatus_Request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetConnectionStatus_Request* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetConnectionStatus_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetConnectionStatus_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetConnectionStatus_Request& from) { GetConnectionStatus_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetConnectionStatus_Request* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.GetConnectionStatus_Request"; }

 protected:
  explicit GetConnectionStatus_Request(::google::protobuf::Arena* arena);
  GetConnectionStatus_Request(::google::protobuf::Arena* arena, const GetConnectionStatus_Request& from);
  GetConnectionStatus_Request(::google::protobuf::Arena* arena, GetConnectionStatus_Request&& from) noexcept
      : GetConnectionStatus_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
    kConnentTypeFieldNumber = 3,
    kConnectVersionFieldNumber = 4,
  };
  // string ip = 1;
  void clear_ip() ;
  const std::string& ip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* value);

  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(
      const std::string& value);
  std::string* _internal_mutable_ip();

  public:
  // uint32 port = 2;
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // .InoRobBusinessGrpc.ConnentType_Grpc connentType = 3;
  void clear_connenttype() ;
  ::InoRobBusinessGrpc::ConnentType_Grpc connenttype() const;
  void set_connenttype(::InoRobBusinessGrpc::ConnentType_Grpc value);

  private:
  ::InoRobBusinessGrpc::ConnentType_Grpc _internal_connenttype() const;
  void _internal_set_connenttype(::InoRobBusinessGrpc::ConnentType_Grpc value);

  public:
  // .InoRobBusinessGrpc.ConnectVersion_Grpc connectVersion = 4;
  void clear_connectversion() ;
  ::InoRobBusinessGrpc::ConnectVersion_Grpc connectversion() const;
  void set_connectversion(::InoRobBusinessGrpc::ConnectVersion_Grpc value);

  private:
  ::InoRobBusinessGrpc::ConnectVersion_Grpc _internal_connectversion() const;
  void _internal_set_connectversion(::InoRobBusinessGrpc::ConnectVersion_Grpc value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.GetConnectionStatus_Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      57, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetConnectionStatus_Request_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetConnectionStatus_Request& from_msg);
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::uint32_t port_;
    int connenttype_;
    int connectversion_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ConnectionGrpc_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GetConnectionStatus_Response

// .InoRobBusinessGrpc.ControllerConnectionStatus_Grpc controllerConnectionStatus = 1;
inline void GetConnectionStatus_Response::clear_controllerconnectionstatus() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.controllerconnectionstatus_ = 0;
}
inline ::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc GetConnectionStatus_Response::controllerconnectionstatus() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetConnectionStatus_Response.controllerConnectionStatus)
  return _internal_controllerconnectionstatus();
}
inline void GetConnectionStatus_Response::set_controllerconnectionstatus(::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc value) {
  _internal_set_controllerconnectionstatus(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetConnectionStatus_Response.controllerConnectionStatus)
}
inline ::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc GetConnectionStatus_Response::_internal_controllerconnectionstatus() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc>(_impl_.controllerconnectionstatus_);
}
inline void GetConnectionStatus_Response::_internal_set_controllerconnectionstatus(::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.controllerconnectionstatus_ = value;
}

// -------------------------------------------------------------------

// GetConnectionStatus_Request

// string ip = 1;
inline void GetConnectionStatus_Request::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& GetConnectionStatus_Request::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetConnectionStatus_Request.ip)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GetConnectionStatus_Request::set_ip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetConnectionStatus_Request.ip)
}
inline std::string* GetConnectionStatus_Request::mutable_ip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:InoRobBusinessGrpc.GetConnectionStatus_Request.ip)
  return _s;
}
inline const std::string& GetConnectionStatus_Request::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void GetConnectionStatus_Request::_internal_set_ip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline std::string* GetConnectionStatus_Request::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline std::string* GetConnectionStatus_Request::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:InoRobBusinessGrpc.GetConnectionStatus_Request.ip)
  return _impl_.ip_.Release();
}
inline void GetConnectionStatus_Request::set_allocated_ip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.ip_.IsDefault()) {
          _impl_.ip_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:InoRobBusinessGrpc.GetConnectionStatus_Request.ip)
}

// uint32 port = 2;
inline void GetConnectionStatus_Request::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
}
inline ::uint32_t GetConnectionStatus_Request::port() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetConnectionStatus_Request.port)
  return _internal_port();
}
inline void GetConnectionStatus_Request::set_port(::uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetConnectionStatus_Request.port)
}
inline ::uint32_t GetConnectionStatus_Request::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void GetConnectionStatus_Request::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// .InoRobBusinessGrpc.ConnentType_Grpc connentType = 3;
inline void GetConnectionStatus_Request::clear_connenttype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connenttype_ = 0;
}
inline ::InoRobBusinessGrpc::ConnentType_Grpc GetConnectionStatus_Request::connenttype() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetConnectionStatus_Request.connentType)
  return _internal_connenttype();
}
inline void GetConnectionStatus_Request::set_connenttype(::InoRobBusinessGrpc::ConnentType_Grpc value) {
  _internal_set_connenttype(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetConnectionStatus_Request.connentType)
}
inline ::InoRobBusinessGrpc::ConnentType_Grpc GetConnectionStatus_Request::_internal_connenttype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::InoRobBusinessGrpc::ConnentType_Grpc>(_impl_.connenttype_);
}
inline void GetConnectionStatus_Request::_internal_set_connenttype(::InoRobBusinessGrpc::ConnentType_Grpc value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connenttype_ = value;
}

// .InoRobBusinessGrpc.ConnectVersion_Grpc connectVersion = 4;
inline void GetConnectionStatus_Request::clear_connectversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connectversion_ = 0;
}
inline ::InoRobBusinessGrpc::ConnectVersion_Grpc GetConnectionStatus_Request::connectversion() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.GetConnectionStatus_Request.connectVersion)
  return _internal_connectversion();
}
inline void GetConnectionStatus_Request::set_connectversion(::InoRobBusinessGrpc::ConnectVersion_Grpc value) {
  _internal_set_connectversion(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.GetConnectionStatus_Request.connectVersion)
}
inline ::InoRobBusinessGrpc::ConnectVersion_Grpc GetConnectionStatus_Request::_internal_connectversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::InoRobBusinessGrpc::ConnectVersion_Grpc>(_impl_.connectversion_);
}
inline void GetConnectionStatus_Request::_internal_set_connectversion(::InoRobBusinessGrpc::ConnectVersion_Grpc value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connectversion_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace InoRobBusinessGrpc


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc>() {
  return ::InoRobBusinessGrpc::ControllerConnectionStatus_Grpc_descriptor();
}
template <>
struct is_proto_enum<::InoRobBusinessGrpc::ConnentType_Grpc> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::InoRobBusinessGrpc::ConnentType_Grpc>() {
  return ::InoRobBusinessGrpc::ConnentType_Grpc_descriptor();
}
template <>
struct is_proto_enum<::InoRobBusinessGrpc::ConnectVersion_Grpc> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::InoRobBusinessGrpc::ConnectVersion_Grpc>() {
  return ::InoRobBusinessGrpc::ConnectVersion_Grpc_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ConnectionGrpc_2eproto_2epb_2eh
