[TeachPadVersion]
Version=V4R26C1SPC0L1F1B5
Vendor=Inovance
Type=WNR
Des=2024-08-20_09:00:00
InoRobotLabVersion=0.0.0.0
CompatibleVersion=S03.22,S03.23,S03.24
FileVersion=V4R24
;版本说明
;格式: A.B.C.D
;A: 例如S03，用3表示
;B: 大版本号: 20,21等等
;C: 次版本号：例如，T01-001，R-100, R01-101, N01-201
;D: 生成号：L0-000,L1-001,L2-002...   A-101,B-102  A_L0-10100, A_L1-10101，R版本段省去
;CompatibleVersion：当前版本在工程方面兼容的旧版本合集，若有多个兼容版本，则以英文逗号','分隔开
