// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: LoadGrpc.proto
// Protobuf C++ Version: 5.28.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_LoadGrpc_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_LoadGrpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/wrappers.pb.h"
#include "../../GrpcService/GlobalDataTypesGrpc.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_LoadGrpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_LoadGrpc_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_LoadGrpc_2eproto;
namespace InoRobBusinessGrpc {
class LoadGrpc_GetLoadParam_Response;
struct LoadGrpc_GetLoadParam_ResponseDefaultTypeInternal;
extern LoadGrpc_GetLoadParam_ResponseDefaultTypeInternal _LoadGrpc_GetLoadParam_Response_default_instance_;
class LoadGrpc_SetLoadParam_Request;
struct LoadGrpc_SetLoadParam_RequestDefaultTypeInternal;
extern LoadGrpc_SetLoadParam_RequestDefaultTypeInternal _LoadGrpc_SetLoadParam_Request_default_instance_;
}  // namespace InoRobBusinessGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace InoRobBusinessGrpc {

// ===================================================================


// -------------------------------------------------------------------

class LoadGrpc_SetLoadParam_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request) */ {
 public:
  inline LoadGrpc_SetLoadParam_Request() : LoadGrpc_SetLoadParam_Request(nullptr) {}
  ~LoadGrpc_SetLoadParam_Request() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LoadGrpc_SetLoadParam_Request(
      ::google::protobuf::internal::ConstantInitialized);

  inline LoadGrpc_SetLoadParam_Request(const LoadGrpc_SetLoadParam_Request& from) : LoadGrpc_SetLoadParam_Request(nullptr, from) {}
  inline LoadGrpc_SetLoadParam_Request(LoadGrpc_SetLoadParam_Request&& from) noexcept
      : LoadGrpc_SetLoadParam_Request(nullptr, std::move(from)) {}
  inline LoadGrpc_SetLoadParam_Request& operator=(const LoadGrpc_SetLoadParam_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadGrpc_SetLoadParam_Request& operator=(LoadGrpc_SetLoadParam_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoadGrpc_SetLoadParam_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoadGrpc_SetLoadParam_Request* internal_default_instance() {
    return reinterpret_cast<const LoadGrpc_SetLoadParam_Request*>(
        &_LoadGrpc_SetLoadParam_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(LoadGrpc_SetLoadParam_Request& a, LoadGrpc_SetLoadParam_Request& b) { a.Swap(&b); }
  inline void Swap(LoadGrpc_SetLoadParam_Request* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadGrpc_SetLoadParam_Request* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoadGrpc_SetLoadParam_Request* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<LoadGrpc_SetLoadParam_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LoadGrpc_SetLoadParam_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LoadGrpc_SetLoadParam_Request& from) { LoadGrpc_SetLoadParam_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(LoadGrpc_SetLoadParam_Request* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request"; }

 protected:
  explicit LoadGrpc_SetLoadParam_Request(::google::protobuf::Arena* arena);
  LoadGrpc_SetLoadParam_Request(::google::protobuf::Arena* arena, const LoadGrpc_SetLoadParam_Request& from);
  LoadGrpc_SetLoadParam_Request(::google::protobuf::Arena* arena, LoadGrpc_SetLoadParam_Request&& from) noexcept
      : LoadGrpc_SetLoadParam_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLoadDataFieldNumber = 2,
    kLoadNoFieldNumber = 1,
  };
  // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
  bool has_loaddata() const;
  void clear_loaddata() ;
  const ::InoRobBusinessGrpc::LoadData_Grpc& loaddata() const;
  PROTOBUF_NODISCARD ::InoRobBusinessGrpc::LoadData_Grpc* release_loaddata();
  ::InoRobBusinessGrpc::LoadData_Grpc* mutable_loaddata();
  void set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value);
  void unsafe_arena_set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value);
  ::InoRobBusinessGrpc::LoadData_Grpc* unsafe_arena_release_loaddata();

  private:
  const ::InoRobBusinessGrpc::LoadData_Grpc& _internal_loaddata() const;
  ::InoRobBusinessGrpc::LoadData_Grpc* _internal_mutable_loaddata();

  public:
  // uint32 loadNo = 1;
  void clear_loadno() ;
  ::uint32_t loadno() const;
  void set_loadno(::uint32_t value);

  private:
  ::uint32_t _internal_loadno() const;
  void _internal_set_loadno(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_LoadGrpc_SetLoadParam_Request_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LoadGrpc_SetLoadParam_Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::InoRobBusinessGrpc::LoadData_Grpc* loaddata_;
    ::uint32_t loadno_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LoadGrpc_2eproto;
};
// -------------------------------------------------------------------

class LoadGrpc_GetLoadParam_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response) */ {
 public:
  inline LoadGrpc_GetLoadParam_Response() : LoadGrpc_GetLoadParam_Response(nullptr) {}
  ~LoadGrpc_GetLoadParam_Response() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LoadGrpc_GetLoadParam_Response(
      ::google::protobuf::internal::ConstantInitialized);

  inline LoadGrpc_GetLoadParam_Response(const LoadGrpc_GetLoadParam_Response& from) : LoadGrpc_GetLoadParam_Response(nullptr, from) {}
  inline LoadGrpc_GetLoadParam_Response(LoadGrpc_GetLoadParam_Response&& from) noexcept
      : LoadGrpc_GetLoadParam_Response(nullptr, std::move(from)) {}
  inline LoadGrpc_GetLoadParam_Response& operator=(const LoadGrpc_GetLoadParam_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadGrpc_GetLoadParam_Response& operator=(LoadGrpc_GetLoadParam_Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoadGrpc_GetLoadParam_Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoadGrpc_GetLoadParam_Response* internal_default_instance() {
    return reinterpret_cast<const LoadGrpc_GetLoadParam_Response*>(
        &_LoadGrpc_GetLoadParam_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LoadGrpc_GetLoadParam_Response& a, LoadGrpc_GetLoadParam_Response& b) { a.Swap(&b); }
  inline void Swap(LoadGrpc_GetLoadParam_Response* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadGrpc_GetLoadParam_Response* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoadGrpc_GetLoadParam_Response* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<LoadGrpc_GetLoadParam_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LoadGrpc_GetLoadParam_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LoadGrpc_GetLoadParam_Response& from) { LoadGrpc_GetLoadParam_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(LoadGrpc_GetLoadParam_Response* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response"; }

 protected:
  explicit LoadGrpc_GetLoadParam_Response(::google::protobuf::Arena* arena);
  LoadGrpc_GetLoadParam_Response(::google::protobuf::Arena* arena, const LoadGrpc_GetLoadParam_Response& from);
  LoadGrpc_GetLoadParam_Response(::google::protobuf::Arena* arena, LoadGrpc_GetLoadParam_Response&& from) noexcept
      : LoadGrpc_GetLoadParam_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLoadDataFieldNumber = 2,
    kRetFieldNumber = 1,
  };
  // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
  bool has_loaddata() const;
  void clear_loaddata() ;
  const ::InoRobBusinessGrpc::LoadData_Grpc& loaddata() const;
  PROTOBUF_NODISCARD ::InoRobBusinessGrpc::LoadData_Grpc* release_loaddata();
  ::InoRobBusinessGrpc::LoadData_Grpc* mutable_loaddata();
  void set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value);
  void unsafe_arena_set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value);
  ::InoRobBusinessGrpc::LoadData_Grpc* unsafe_arena_release_loaddata();

  private:
  const ::InoRobBusinessGrpc::LoadData_Grpc& _internal_loaddata() const;
  ::InoRobBusinessGrpc::LoadData_Grpc* _internal_mutable_loaddata();

  public:
  // bool ret = 1;
  void clear_ret() ;
  bool ret() const;
  void set_ret(bool value);

  private:
  bool _internal_ret() const;
  void _internal_set_ret(bool value);

  public:
  // @@protoc_insertion_point(class_scope:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_LoadGrpc_GetLoadParam_Response_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LoadGrpc_GetLoadParam_Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::InoRobBusinessGrpc::LoadData_Grpc* loaddata_;
    bool ret_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LoadGrpc_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LoadGrpc_GetLoadParam_Response

// bool ret = 1;
inline void LoadGrpc_GetLoadParam_Response::clear_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_ = false;
}
inline bool LoadGrpc_GetLoadParam_Response::ret() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.ret)
  return _internal_ret();
}
inline void LoadGrpc_GetLoadParam_Response::set_ret(bool value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.ret)
}
inline bool LoadGrpc_GetLoadParam_Response::_internal_ret() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ret_;
}
inline void LoadGrpc_GetLoadParam_Response::_internal_set_ret(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_ = value;
}

// .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
inline bool LoadGrpc_GetLoadParam_Response::has_loaddata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.loaddata_ != nullptr);
  return value;
}
inline const ::InoRobBusinessGrpc::LoadData_Grpc& LoadGrpc_GetLoadParam_Response::_internal_loaddata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::InoRobBusinessGrpc::LoadData_Grpc* p = _impl_.loaddata_;
  return p != nullptr ? *p : reinterpret_cast<const ::InoRobBusinessGrpc::LoadData_Grpc&>(::InoRobBusinessGrpc::_LoadData_Grpc_default_instance_);
}
inline const ::InoRobBusinessGrpc::LoadData_Grpc& LoadGrpc_GetLoadParam_Response::loaddata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.loadData)
  return _internal_loaddata();
}
inline void LoadGrpc_GetLoadParam_Response::unsafe_arena_set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.loaddata_);
  }
  _impl_.loaddata_ = reinterpret_cast<::InoRobBusinessGrpc::LoadData_Grpc*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.loadData)
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_GetLoadParam_Response::release_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::InoRobBusinessGrpc::LoadData_Grpc* released = _impl_.loaddata_;
  _impl_.loaddata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_GetLoadParam_Response::unsafe_arena_release_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.loadData)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::InoRobBusinessGrpc::LoadData_Grpc* temp = _impl_.loaddata_;
  _impl_.loaddata_ = nullptr;
  return temp;
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_GetLoadParam_Response::_internal_mutable_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.loaddata_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::InoRobBusinessGrpc::LoadData_Grpc>(GetArena());
    _impl_.loaddata_ = reinterpret_cast<::InoRobBusinessGrpc::LoadData_Grpc*>(p);
  }
  return _impl_.loaddata_;
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_GetLoadParam_Response::mutable_loaddata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::InoRobBusinessGrpc::LoadData_Grpc* _msg = _internal_mutable_loaddata();
  // @@protoc_insertion_point(field_mutable:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.loadData)
  return _msg;
}
inline void LoadGrpc_GetLoadParam_Response::set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.loaddata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.loaddata_ = reinterpret_cast<::InoRobBusinessGrpc::LoadData_Grpc*>(value);
  // @@protoc_insertion_point(field_set_allocated:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response.loadData)
}

// -------------------------------------------------------------------

// LoadGrpc_SetLoadParam_Request

// uint32 loadNo = 1;
inline void LoadGrpc_SetLoadParam_Request::clear_loadno() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loadno_ = 0u;
}
inline ::uint32_t LoadGrpc_SetLoadParam_Request::loadno() const {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadNo)
  return _internal_loadno();
}
inline void LoadGrpc_SetLoadParam_Request::set_loadno(::uint32_t value) {
  _internal_set_loadno(value);
  // @@protoc_insertion_point(field_set:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadNo)
}
inline ::uint32_t LoadGrpc_SetLoadParam_Request::_internal_loadno() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.loadno_;
}
inline void LoadGrpc_SetLoadParam_Request::_internal_set_loadno(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loadno_ = value;
}

// .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
inline bool LoadGrpc_SetLoadParam_Request::has_loaddata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.loaddata_ != nullptr);
  return value;
}
inline const ::InoRobBusinessGrpc::LoadData_Grpc& LoadGrpc_SetLoadParam_Request::_internal_loaddata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::InoRobBusinessGrpc::LoadData_Grpc* p = _impl_.loaddata_;
  return p != nullptr ? *p : reinterpret_cast<const ::InoRobBusinessGrpc::LoadData_Grpc&>(::InoRobBusinessGrpc::_LoadData_Grpc_default_instance_);
}
inline const ::InoRobBusinessGrpc::LoadData_Grpc& LoadGrpc_SetLoadParam_Request::loaddata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadData)
  return _internal_loaddata();
}
inline void LoadGrpc_SetLoadParam_Request::unsafe_arena_set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.loaddata_);
  }
  _impl_.loaddata_ = reinterpret_cast<::InoRobBusinessGrpc::LoadData_Grpc*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadData)
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_SetLoadParam_Request::release_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::InoRobBusinessGrpc::LoadData_Grpc* released = _impl_.loaddata_;
  _impl_.loaddata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_SetLoadParam_Request::unsafe_arena_release_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadData)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::InoRobBusinessGrpc::LoadData_Grpc* temp = _impl_.loaddata_;
  _impl_.loaddata_ = nullptr;
  return temp;
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_SetLoadParam_Request::_internal_mutable_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.loaddata_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::InoRobBusinessGrpc::LoadData_Grpc>(GetArena());
    _impl_.loaddata_ = reinterpret_cast<::InoRobBusinessGrpc::LoadData_Grpc*>(p);
  }
  return _impl_.loaddata_;
}
inline ::InoRobBusinessGrpc::LoadData_Grpc* LoadGrpc_SetLoadParam_Request::mutable_loaddata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::InoRobBusinessGrpc::LoadData_Grpc* _msg = _internal_mutable_loaddata();
  // @@protoc_insertion_point(field_mutable:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadData)
  return _msg;
}
inline void LoadGrpc_SetLoadParam_Request::set_allocated_loaddata(::InoRobBusinessGrpc::LoadData_Grpc* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.loaddata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.loaddata_ = reinterpret_cast<::InoRobBusinessGrpc::LoadData_Grpc*>(value);
  // @@protoc_insertion_point(field_set_allocated:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request.loadData)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace InoRobBusinessGrpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_LoadGrpc_2eproto_2epb_2eh
