// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: LoadGrpc.proto
// Protobuf C++ Version: 5.28.1

#include "LoadGrpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace InoRobBusinessGrpc {

inline constexpr LoadGrpc_SetLoadParam_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        loaddata_{nullptr},
        loadno_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR LoadGrpc_SetLoadParam_Request::LoadGrpc_SetLoadParam_Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LoadGrpc_SetLoadParam_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoadGrpc_SetLoadParam_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoadGrpc_SetLoadParam_RequestDefaultTypeInternal() {}
  union {
    LoadGrpc_SetLoadParam_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoadGrpc_SetLoadParam_RequestDefaultTypeInternal _LoadGrpc_SetLoadParam_Request_default_instance_;

inline constexpr LoadGrpc_GetLoadParam_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        loaddata_{nullptr},
        ret_{false} {}

template <typename>
PROTOBUF_CONSTEXPR LoadGrpc_GetLoadParam_Response::LoadGrpc_GetLoadParam_Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LoadGrpc_GetLoadParam_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoadGrpc_GetLoadParam_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoadGrpc_GetLoadParam_ResponseDefaultTypeInternal() {}
  union {
    LoadGrpc_GetLoadParam_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoadGrpc_GetLoadParam_ResponseDefaultTypeInternal _LoadGrpc_GetLoadParam_Response_default_instance_;
}  // namespace InoRobBusinessGrpc
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_LoadGrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_LoadGrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_LoadGrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response, _impl_.ret_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response, _impl_.loaddata_),
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request, _impl_.loadno_),
        PROTOBUF_FIELD_OFFSET(::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request, _impl_.loaddata_),
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response)},
        {12, 22, -1, sizeof(::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::InoRobBusinessGrpc::_LoadGrpc_GetLoadParam_Response_default_instance_._instance,
    &::InoRobBusinessGrpc::_LoadGrpc_SetLoadParam_Request_default_instance_._instance,
};
const char descriptor_table_protodef_LoadGrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016LoadGrpc.proto\022\022InoRobBusinessGrpc\032\033go"
    "ogle/protobuf/empty.proto\032\036google/protob"
    "uf/wrappers.proto\032\031GlobalDataTypesGrpc.p"
    "roto\"b\n\036LoadGrpc_GetLoadParam_Response\022\013"
    "\n\003ret\030\001 \001(\010\0223\n\010loadData\030\002 \001(\0132!.InoRobBu"
    "sinessGrpc.LoadData_Grpc\"d\n\035LoadGrpc_Set"
    "LoadParam_Request\022\016\n\006loadNo\030\001 \001(\r\0223\n\010loa"
    "dData\030\002 \001(\0132!.InoRobBusinessGrpc.LoadDat"
    "a_Grpc2\233\002\n\010LoadGrpc\022J\n\014SetCurrentId\022\034.go"
    "ogle.protobuf.UInt32Value\032\032.google.proto"
    "buf.BoolValue\"\000\022b\n\014GetLoadParam\022\034.google"
    ".protobuf.UInt32Value\0322.InoRobBusinessGr"
    "pc.LoadGrpc_GetLoadParam_Response\"\000\022_\n\014S"
    "etLoadParam\0221.InoRobBusinessGrpc.LoadGrp"
    "c_SetLoadParam_Request\032\032.google.protobuf"
    ".BoolValue\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_LoadGrpc_2eproto_deps[3] =
    {
        &::descriptor_table_GlobalDataTypesGrpc_2eproto,
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::absl::once_flag descriptor_table_LoadGrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_LoadGrpc_2eproto = {
    false,
    false,
    620,
    descriptor_table_protodef_LoadGrpc_2eproto,
    "LoadGrpc.proto",
    &descriptor_table_LoadGrpc_2eproto_once,
    descriptor_table_LoadGrpc_2eproto_deps,
    3,
    2,
    schemas,
    file_default_instances,
    TableStruct_LoadGrpc_2eproto::offsets,
    file_level_enum_descriptors_LoadGrpc_2eproto,
    file_level_service_descriptors_LoadGrpc_2eproto,
};
namespace InoRobBusinessGrpc {
// ===================================================================

class LoadGrpc_GetLoadParam_Response::_Internal {
 public:
  using HasBits =
      decltype(std::declval<LoadGrpc_GetLoadParam_Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_._has_bits_);
};

void LoadGrpc_GetLoadParam_Response::clear_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.loaddata_ != nullptr) _impl_.loaddata_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
LoadGrpc_GetLoadParam_Response::LoadGrpc_GetLoadParam_Response(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
}
inline PROTOBUF_NDEBUG_INLINE LoadGrpc_GetLoadParam_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

LoadGrpc_GetLoadParam_Response::LoadGrpc_GetLoadParam_Response(
    ::google::protobuf::Arena* arena,
    const LoadGrpc_GetLoadParam_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LoadGrpc_GetLoadParam_Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.loaddata_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::InoRobBusinessGrpc::LoadData_Grpc>(
                              arena, *from._impl_.loaddata_)
                        : nullptr;
  _impl_.ret_ = from._impl_.ret_;

  // @@protoc_insertion_point(copy_constructor:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
}
inline PROTOBUF_NDEBUG_INLINE LoadGrpc_GetLoadParam_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LoadGrpc_GetLoadParam_Response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, loaddata_),
           0,
           offsetof(Impl_, ret_) -
               offsetof(Impl_, loaddata_) +
               sizeof(Impl_::ret_));
}
LoadGrpc_GetLoadParam_Response::~LoadGrpc_GetLoadParam_Response() {
  // @@protoc_insertion_point(destructor:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoadGrpc_GetLoadParam_Response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.loaddata_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    LoadGrpc_GetLoadParam_Response::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_LoadGrpc_GetLoadParam_Response_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &LoadGrpc_GetLoadParam_Response::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<LoadGrpc_GetLoadParam_Response>(),
            ::google::protobuf::Message::GetNewImpl<LoadGrpc_GetLoadParam_Response>(),
            ::google::protobuf::Message::GetClearImpl<LoadGrpc_GetLoadParam_Response>(), &LoadGrpc_GetLoadParam_Response::ByteSizeLong,
                &LoadGrpc_GetLoadParam_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_._cached_size_),
            false,
        },
        &LoadGrpc_GetLoadParam_Response::kDescriptorMethods,
        &descriptor_table_LoadGrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* LoadGrpc_GetLoadParam_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> LoadGrpc_GetLoadParam_Response::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::LoadGrpc_GetLoadParam_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_.loaddata_)}},
    // bool ret = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LoadGrpc_GetLoadParam_Response, _impl_.ret_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_.ret_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ret = 1;
    {PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_.ret_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
    {PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_.loaddata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::LoadData_Grpc>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void LoadGrpc_GetLoadParam_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.loaddata_ != nullptr);
    _impl_.loaddata_->Clear();
  }
  _impl_.ret_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LoadGrpc_GetLoadParam_Response::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LoadGrpc_GetLoadParam_Response& this_ = static_cast<const LoadGrpc_GetLoadParam_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LoadGrpc_GetLoadParam_Response::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LoadGrpc_GetLoadParam_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool ret = 1;
          if (this_._internal_ret() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_ret(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.loaddata_, this_._impl_.loaddata_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LoadGrpc_GetLoadParam_Response::ByteSizeLong(const MessageLite& base) {
          const LoadGrpc_GetLoadParam_Response& this_ = static_cast<const LoadGrpc_GetLoadParam_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LoadGrpc_GetLoadParam_Response::ByteSizeLong() const {
          const LoadGrpc_GetLoadParam_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.loaddata_);
            }
          }
           {
            // bool ret = 1;
            if (this_._internal_ret() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LoadGrpc_GetLoadParam_Response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LoadGrpc_GetLoadParam_Response*>(&to_msg);
  auto& from = static_cast<const LoadGrpc_GetLoadParam_Response&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.loaddata_ != nullptr);
    if (_this->_impl_.loaddata_ == nullptr) {
      _this->_impl_.loaddata_ =
          ::google::protobuf::Message::CopyConstruct<::InoRobBusinessGrpc::LoadData_Grpc>(arena, *from._impl_.loaddata_);
    } else {
      _this->_impl_.loaddata_->MergeFrom(*from._impl_.loaddata_);
    }
  }
  if (from._internal_ret() != 0) {
    _this->_impl_.ret_ = from._impl_.ret_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoadGrpc_GetLoadParam_Response::CopyFrom(const LoadGrpc_GetLoadParam_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InoRobBusinessGrpc.LoadGrpc_GetLoadParam_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LoadGrpc_GetLoadParam_Response::InternalSwap(LoadGrpc_GetLoadParam_Response* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_.ret_)
      + sizeof(LoadGrpc_GetLoadParam_Response::_impl_.ret_)
      - PROTOBUF_FIELD_OFFSET(LoadGrpc_GetLoadParam_Response, _impl_.loaddata_)>(
          reinterpret_cast<char*>(&_impl_.loaddata_),
          reinterpret_cast<char*>(&other->_impl_.loaddata_));
}

::google::protobuf::Metadata LoadGrpc_GetLoadParam_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LoadGrpc_SetLoadParam_Request::_Internal {
 public:
  using HasBits =
      decltype(std::declval<LoadGrpc_SetLoadParam_Request>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_._has_bits_);
};

void LoadGrpc_SetLoadParam_Request::clear_loaddata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.loaddata_ != nullptr) _impl_.loaddata_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
LoadGrpc_SetLoadParam_Request::LoadGrpc_SetLoadParam_Request(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
}
inline PROTOBUF_NDEBUG_INLINE LoadGrpc_SetLoadParam_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

LoadGrpc_SetLoadParam_Request::LoadGrpc_SetLoadParam_Request(
    ::google::protobuf::Arena* arena,
    const LoadGrpc_SetLoadParam_Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LoadGrpc_SetLoadParam_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.loaddata_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::InoRobBusinessGrpc::LoadData_Grpc>(
                              arena, *from._impl_.loaddata_)
                        : nullptr;
  _impl_.loadno_ = from._impl_.loadno_;

  // @@protoc_insertion_point(copy_constructor:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
}
inline PROTOBUF_NDEBUG_INLINE LoadGrpc_SetLoadParam_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LoadGrpc_SetLoadParam_Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, loaddata_),
           0,
           offsetof(Impl_, loadno_) -
               offsetof(Impl_, loaddata_) +
               sizeof(Impl_::loadno_));
}
LoadGrpc_SetLoadParam_Request::~LoadGrpc_SetLoadParam_Request() {
  // @@protoc_insertion_point(destructor:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoadGrpc_SetLoadParam_Request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.loaddata_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    LoadGrpc_SetLoadParam_Request::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_LoadGrpc_SetLoadParam_Request_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &LoadGrpc_SetLoadParam_Request::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<LoadGrpc_SetLoadParam_Request>(),
            ::google::protobuf::Message::GetNewImpl<LoadGrpc_SetLoadParam_Request>(),
            ::google::protobuf::Message::GetClearImpl<LoadGrpc_SetLoadParam_Request>(), &LoadGrpc_SetLoadParam_Request::ByteSizeLong,
                &LoadGrpc_SetLoadParam_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_._cached_size_),
            false,
        },
        &LoadGrpc_SetLoadParam_Request::kDescriptorMethods,
        &descriptor_table_LoadGrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* LoadGrpc_SetLoadParam_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> LoadGrpc_SetLoadParam_Request::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::LoadGrpc_SetLoadParam_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_.loaddata_)}},
    // uint32 loadNo = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoadGrpc_SetLoadParam_Request, _impl_.loadno_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_.loadno_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 loadNo = 1;
    {PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_.loadno_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
    {PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_.loaddata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::InoRobBusinessGrpc::LoadData_Grpc>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void LoadGrpc_SetLoadParam_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.loaddata_ != nullptr);
    _impl_.loaddata_->Clear();
  }
  _impl_.loadno_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LoadGrpc_SetLoadParam_Request::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LoadGrpc_SetLoadParam_Request& this_ = static_cast<const LoadGrpc_SetLoadParam_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LoadGrpc_SetLoadParam_Request::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LoadGrpc_SetLoadParam_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 loadNo = 1;
          if (this_._internal_loadno() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_loadno(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.loaddata_, this_._impl_.loaddata_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LoadGrpc_SetLoadParam_Request::ByteSizeLong(const MessageLite& base) {
          const LoadGrpc_SetLoadParam_Request& this_ = static_cast<const LoadGrpc_SetLoadParam_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LoadGrpc_SetLoadParam_Request::ByteSizeLong() const {
          const LoadGrpc_SetLoadParam_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .InoRobBusinessGrpc.LoadData_Grpc loadData = 2;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.loaddata_);
            }
          }
           {
            // uint32 loadNo = 1;
            if (this_._internal_loadno() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_loadno());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LoadGrpc_SetLoadParam_Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LoadGrpc_SetLoadParam_Request*>(&to_msg);
  auto& from = static_cast<const LoadGrpc_SetLoadParam_Request&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.loaddata_ != nullptr);
    if (_this->_impl_.loaddata_ == nullptr) {
      _this->_impl_.loaddata_ =
          ::google::protobuf::Message::CopyConstruct<::InoRobBusinessGrpc::LoadData_Grpc>(arena, *from._impl_.loaddata_);
    } else {
      _this->_impl_.loaddata_->MergeFrom(*from._impl_.loaddata_);
    }
  }
  if (from._internal_loadno() != 0) {
    _this->_impl_.loadno_ = from._impl_.loadno_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoadGrpc_SetLoadParam_Request::CopyFrom(const LoadGrpc_SetLoadParam_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InoRobBusinessGrpc.LoadGrpc_SetLoadParam_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LoadGrpc_SetLoadParam_Request::InternalSwap(LoadGrpc_SetLoadParam_Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_.loadno_)
      + sizeof(LoadGrpc_SetLoadParam_Request::_impl_.loadno_)
      - PROTOBUF_FIELD_OFFSET(LoadGrpc_SetLoadParam_Request, _impl_.loaddata_)>(
          reinterpret_cast<char*>(&_impl_.loaddata_),
          reinterpret_cast<char*>(&other->_impl_.loaddata_));
}

::google::protobuf::Metadata LoadGrpc_SetLoadParam_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace InoRobBusinessGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_LoadGrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
