set(COBOT_TP_APP_TARGET "${COBOT_TP_APP_TARGET}")
set(SOURCE_FILE_BIN "${SOURCE_FILE_BIN}")
set(DESTINATION_FILE_BIN "${DESTINATION_FILE_BIN}")
set(LIB_ENABLED_LIST_ON_STR "${LIB_ENABLED_LIST_ON_STR}")
set(BIN_LIB_DLL_DIFFERENCE_STR "${BIN_LIB_DLL_DIFFERENCE_STR}")
set(PLUGIN_ENABLED_LIST_ON_STR "${PLUGIN_ENABLED_LIST_ON_STR}")


#lib
set(LIB_ENABLED_LIST_DLL)
set(LIB_ENABLED_LIST_A)
string(REPLACE "," ";" LIB_ENABLED_LIST_ON "${LIB_ENABLED_LIST_ON_STR}")
foreach(LIB ${LIB_ENABLED_LIST_ON})
    string(REPLACE "CommonLib_" "lib" TEMP ${LIB})
    string(REPLACE "_Enabled" "" RESULT ${TEMP})
    set(LIB_DLL "${RESULT}.dll")
    set(LIB_DLL_A "${LIB_DLL}.a")
    set(SOURCE_LIB_DLL ${SOURCE_FILE_BIN}/${LIB_DLL})
    set(SOURCE_LIB_DLL_A ${SOURCE_FILE_BIN}/libs/${LIB_DLL_A})

    list(APPEND LIB_ENABLED_LIST_DLL ${SOURCE_LIB_DLL})
    list(APPEND LIB_ENABLED_LIST_A ${SOURCE_LIB_DLL_A})
endforeach()

foreach(LIB_A ${LIB_ENABLED_LIST_A})
    file(COPY ${LIB_A} DESTINATION ${DESTINATION_FILE_BIN}/libs)
endforeach()
foreach(LIB_DLL ${LIB_ENABLED_LIST_DLL})
    file(COPY ${LIB_DLL} DESTINATION ${DESTINATION_FILE_BIN})
endforeach()

#
set(LIB_BIN_LIST)
string(REPLACE "," ";" BIN_LIB_DLL_DIFFERENCE "${BIN_LIB_DLL_DIFFERENCE_STR}")
foreach(LIB ${BIN_LIB_DLL_DIFFERENCE})
    set(LIB_DLL "${LIB}.dll")
    set(SOURCE_LIB_DLL ${SOURCE_FILE_BIN}/${LIB_DLL})

    list(APPEND LIB_BIN_LIST ${SOURCE_LIB_DLL})
endforeach()

foreach(LIB ${LIB_BIN_LIST})
    file(COPY ${LIB} DESTINATION ${DESTINATION_FILE_BIN})
endforeach()

#Plugins
set(PLUGIN_ENABLED_LIST_DLL)
set(PLUGIN_ENABLED_LIST_A)
string(REPLACE "," ";" PLUGIN_ENABLED_LIST_ON "${PLUGIN_ENABLED_LIST_ON_STR}")
foreach(PLUGIN ${PLUGIN_ENABLED_LIST_ON})
    string(REPLACE "PluginLib_" "lib" TEMP ${PLUGIN})
    string(REPLACE "_Enabled" "" RESULT ${TEMP})
    set(PLUGIN_DLL "${RESULT}.dll")
    set(PLUGIN_DLL_A "${PLUGIN_DLL}.a")
    set(SOURCE_PLUGIN_DLL ${SOURCE_FILE_BIN}/plugins/${PLUGIN_DLL})
    set(SOURCE_PLUGIN_DLL_A ${SOURCE_FILE_BIN}/plugins/${PLUGIN_DLL_A})

    list(APPEND PLUGIN_ENABLED_LIST_DLL ${SOURCE_PLUGIN_DLL})
    list(APPEND PLUGIN_ENABLED_LIST_A ${SOURCE_PLUGIN_DLL_A})
endforeach()

foreach(PLUGIN_DLL ${PLUGIN_ENABLED_LIST_DLL})
    file(COPY ${PLUGIN_DLL} DESTINATION ${DESTINATION_FILE_BIN}/plugins)
endforeach()
foreach(PLUGIN_A ${PLUGIN_ENABLED_LIST_A})
    file(COPY ${PLUGIN_A} DESTINATION ${DESTINATION_FILE_BIN}/plugins)
endforeach()

#Target.exe
file(COPY ${SOURCE_FILE_BIN}/${COBOT_TP_APP_TARGET}.exe DESTINATION ${DESTINATION_FILE_BIN})
