#pragma once

#ifdef _WIN32
    #include <sdkddkver.h>
#endif

#include "../Controller/Connection/IConnection.h"
#include "../Controller/Monitor/IMonitor.h"
#include "../Controller/DataSubscribe/IDataSubscribe.h"
#include "../Controller/RCScheduler/IRCScheduler.h"
#include "../Controller/RCScheduler/IRCSchedulerUser.h"
#include "../Controller/Control/IControl.h"
#include "../Controller/Position/IPosition.h"
#include "../Controller/RCConfig/IRCConfig.h"
#include "../Controller/Resource/IResource.h"
#include "../Controller/Motion/IMotion.h"
#include "../Controller/RobotArm/IRobotArm.h"
#include "../Controller/Calibrate/ICalibrate.h"
#include "../Controller/Load/ILoad.h"
#include "../Controller/Tool/ITool.h"
#include "../Controller/Wobj/IWobj.h"
#include "../Controller/MechUnit/IMechUnit.h"
#include "../Controller/MechUnit/IMechUnitManage.h"
#include "../Controller/Peripheral/IPeripheral.h"
#include "../Controller/Maintenance/IMaintenance.h"
#include "../Controller/Monitor/IWarnInfo.h"
#include "../Controller/Debuger/IDebuger.h"
#include "../Controller/Task/ITask.h"
#include "../Controller/Transfor/ITransfor.h"
#include "../Controller/ScriptExtension/IScriptExtension.h"
#include "../Controller/LoadIdentify/ILoadIdentify.h"
#include "../Controller/PubSub/ISubscriber.h"
#include "../Controller/FunctionSafe/ISafeParaSettingMgr.h"
#include "../Controller/TrajectoryRecovery/ITrajectoryRecovery.h"
#include "../Controller/Plugin/IInoRobPluginMasterService.h"

#include "../Controller/IController.h"
#include "../Workstation/IWorkstation.h"
#include "../Controller/StatusChecks/StatusChecks.h"
#include "../Controller/Language/LanguageService.h"
#include "../Controller/ForceCtrl/IForceCtrl.h"
#include "../Controller/FrictionCompensation/IFrictionCompensation.h"
#include "../Controller/BacklashCompensation/IBacklashCompensation.h"
#include "comwithTp.h"
