// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: WobjGrpc.proto
#ifndef GRPC_WobjGrpc_2eproto__INCLUDED
#define GRPC_WobjGrpc_2eproto__INCLUDED

#include "WobjGrpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace InoRobBusinessGrpc {

// 工件
class WobjGrpc final {
 public:
  static constexpr char const* service_full_name() {
    return "InoRobBusinessGrpc.WobjGrpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 获取当前工件号
    virtual ::grpc::Status getCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::UInt32Value* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::UInt32Value>> AsyncgetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::UInt32Value>>(AsyncgetCurrentIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::UInt32Value>> PrepareAsyncgetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::UInt32Value>>(PrepareAsyncgetCurrentIdRaw(context, request, cq));
    }
    // 设定当前工件号
    virtual ::grpc::Status SetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::google::protobuf::BoolValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> AsyncSetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(AsyncSetCurrentIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> PrepareAsyncSetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(PrepareAsyncSetCurrentIdRaw(context, request, cq));
    }
    // 当前工件是否为机器人夹持
    virtual ::grpc::Status currentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>> AsynccurrentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>>(AsynccurrentIsRobotHoldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>> PrepareAsynccurrentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>>(PrepareAsynccurrentIsRobotHoldRaw(context, request, cq));
    }
    // 指定工件是否为机器人夹持
    virtual ::grpc::Status someoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>> AsyncsomeoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>>(AsyncsomeoneIsRobotHoldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>> PrepareAsyncsomeoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>>(PrepareAsyncsomeoneIsRobotHoldRaw(context, request, cq));
    }
    // 指定工件是否为固定
    virtual ::grpc::Status someoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>> AsyncsomeoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>>(AsyncsomeoneIsFixedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>> PrepareAsyncsomeoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>>(PrepareAsyncsomeoneIsFixedRaw(context, request, cq));
    }
    // 获取当前的工件参数
    virtual ::grpc::Status GetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>> AsyncGetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>>(AsyncGetCurrentWobjParamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>> PrepareAsyncGetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>>(PrepareAsyncGetCurrentWobjParamRaw(context, request, cq));
    }
    // 读取工件参数
    virtual ::grpc::Status GetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>> AsyncGetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>>(AsyncGetWobjParamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>> PrepareAsyncGetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>>(PrepareAsyncGetWobjParamRaw(context, request, cq));
    }
    // 设置工件参数
    virtual ::grpc::Status SetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::google::protobuf::BoolValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> AsyncSetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(AsyncSetWobjParamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> PrepareAsyncSetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(PrepareAsyncSetWobjParamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 获取当前工件号
      virtual void getCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 设定当前工件号
      virtual void SetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 当前工件是否为机器人夹持
      virtual void currentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void currentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 指定工件是否为机器人夹持
      virtual void someoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void someoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 指定工件是否为固定
      virtual void someoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void someoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取当前的工件参数
      virtual void GetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 读取工件参数
      virtual void GetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 设置工件参数
      virtual void SetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::UInt32Value>* AsyncgetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::UInt32Value>* PrepareAsyncgetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* AsyncSetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* PrepareAsyncSetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* AsynccurrentIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* PrepareAsynccurrentIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* AsyncsomeoneIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* PrepareAsyncsomeoneIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* AsyncsomeoneIsFixedRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* PrepareAsyncsomeoneIsFixedRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* AsyncGetCurrentWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* PrepareAsyncGetCurrentWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* AsyncGetWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* PrepareAsyncGetWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* AsyncSetWobjParamRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* PrepareAsyncSetWobjParamRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::UInt32Value* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>> AsyncgetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>>(AsyncgetCurrentIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>> PrepareAsyncgetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>>(PrepareAsyncgetCurrentIdRaw(context, request, cq));
    }
    ::grpc::Status SetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::google::protobuf::BoolValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> AsyncSetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(AsyncSetCurrentIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> PrepareAsyncSetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(PrepareAsyncSetCurrentIdRaw(context, request, cq));
    }
    ::grpc::Status currentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>> AsynccurrentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>>(AsynccurrentIsRobotHoldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>> PrepareAsynccurrentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>>(PrepareAsynccurrentIsRobotHoldRaw(context, request, cq));
    }
    ::grpc::Status someoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>> AsyncsomeoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>>(AsyncsomeoneIsRobotHoldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>> PrepareAsyncsomeoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>>(PrepareAsyncsomeoneIsRobotHoldRaw(context, request, cq));
    }
    ::grpc::Status someoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>> AsyncsomeoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>>(AsyncsomeoneIsFixedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>> PrepareAsyncsomeoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>>(PrepareAsyncsomeoneIsFixedRaw(context, request, cq));
    }
    ::grpc::Status GetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>> AsyncGetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>>(AsyncGetCurrentWobjParamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>> PrepareAsyncGetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>>(PrepareAsyncGetCurrentWobjParamRaw(context, request, cq));
    }
    ::grpc::Status GetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>> AsyncGetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>>(AsyncGetWobjParamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>> PrepareAsyncGetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>>(PrepareAsyncGetWobjParamRaw(context, request, cq));
    }
    ::grpc::Status SetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::google::protobuf::BoolValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> AsyncSetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(AsyncSetWobjParamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> PrepareAsyncSetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(PrepareAsyncSetWobjParamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)>) override;
      void getCurrentId(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) override;
      void SetCurrentId(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) override;
      void currentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response, std::function<void(::grpc::Status)>) override;
      void currentIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void someoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response, std::function<void(::grpc::Status)>) override;
      void someoneIsRobotHold(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void someoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response, std::function<void(::grpc::Status)>) override;
      void someoneIsFixed(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response, std::function<void(::grpc::Status)>) override;
      void GetCurrentWobjParam(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response, std::function<void(::grpc::Status)>) override;
      void GetWobjParam(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) override;
      void SetWobjParam(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* AsyncgetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* PrepareAsyncgetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* AsyncSetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* PrepareAsyncSetCurrentIdRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* AsynccurrentIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* PrepareAsynccurrentIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* AsyncsomeoneIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* PrepareAsyncsomeoneIsRobotHoldRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* AsyncsomeoneIsFixedRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* PrepareAsyncsomeoneIsFixedRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* AsyncGetCurrentWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* PrepareAsyncGetCurrentWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* AsyncGetWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* PrepareAsyncGetWobjParamRaw(::grpc::ClientContext* context, const ::google::protobuf::UInt32Value& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* AsyncSetWobjParamRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* PrepareAsyncSetWobjParamRaw(::grpc::ClientContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getCurrentId_;
    const ::grpc::internal::RpcMethod rpcmethod_SetCurrentId_;
    const ::grpc::internal::RpcMethod rpcmethod_currentIsRobotHold_;
    const ::grpc::internal::RpcMethod rpcmethod_someoneIsRobotHold_;
    const ::grpc::internal::RpcMethod rpcmethod_someoneIsFixed_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCurrentWobjParam_;
    const ::grpc::internal::RpcMethod rpcmethod_GetWobjParam_;
    const ::grpc::internal::RpcMethod rpcmethod_SetWobjParam_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 获取当前工件号
    virtual ::grpc::Status getCurrentId(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response);
    // 设定当前工件号
    virtual ::grpc::Status SetCurrentId(::grpc::ServerContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::BoolValue* response);
    // 当前工件是否为机器人夹持
    virtual ::grpc::Status currentIsRobotHold(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response);
    // 指定工件是否为机器人夹持
    virtual ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response);
    // 指定工件是否为固定
    virtual ::grpc::Status someoneIsFixed(::grpc::ServerContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response);
    // 获取当前的工件参数
    virtual ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response);
    // 读取工件参数
    virtual ::grpc::Status GetWobjParam(::grpc::ServerContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response);
    // 设置工件参数
    virtual ::grpc::Status SetWobjParam(::grpc::ServerContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::google::protobuf::BoolValue* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getCurrentId() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetCurrentId(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::UInt32Value>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetCurrentId() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetCurrentId(::grpc::ServerContext* context, ::google::protobuf::UInt32Value* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::BoolValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_currentIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_currentIsRobotHold() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_currentIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status currentIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcurrentIsRobotHold(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_someoneIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_someoneIsRobotHold() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_someoneIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsomeoneIsRobotHold(::grpc::ServerContext* context, ::google::protobuf::UInt32Value* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_someoneIsFixed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_someoneIsFixed() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_someoneIsFixed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsFixed(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsomeoneIsFixed(::grpc::ServerContext* context, ::google::protobuf::UInt32Value* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCurrentWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCurrentWobjParam() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_GetCurrentWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCurrentWobjParam(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetWobjParam() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_GetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWobjParam(::grpc::ServerContext* context, ::google::protobuf::UInt32Value* request, ::grpc::ServerAsyncResponseWriter< ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetWobjParam() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_SetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetWobjParam(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetWobjParam(::grpc::ServerContext* context, ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::BoolValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getCurrentId<WithAsyncMethod_SetCurrentId<WithAsyncMethod_currentIsRobotHold<WithAsyncMethod_someoneIsRobotHold<WithAsyncMethod_someoneIsFixed<WithAsyncMethod_GetCurrentWobjParam<WithAsyncMethod_GetWobjParam<WithAsyncMethod_SetWobjParam<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getCurrentId() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::google::protobuf::UInt32Value>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response) { return this->getCurrentId(context, request, response); }));}
    void SetMessageAllocatorFor_getCurrentId(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::google::protobuf::UInt32Value>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::google::protobuf::UInt32Value>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getCurrentId(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetCurrentId() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::google::protobuf::BoolValue>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::UInt32Value* request, ::google::protobuf::BoolValue* response) { return this->SetCurrentId(context, request, response); }));}
    void SetMessageAllocatorFor_SetCurrentId(
        ::grpc::MessageAllocator< ::google::protobuf::UInt32Value, ::google::protobuf::BoolValue>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::google::protobuf::BoolValue>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetCurrentId(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_currentIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_currentIsRobotHold() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* response) { return this->currentIsRobotHold(context, request, response); }));}
    void SetMessageAllocatorFor_currentIsRobotHold(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_currentIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status currentIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* currentIsRobotHold(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_someoneIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_someoneIsRobotHold() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* response) { return this->someoneIsRobotHold(context, request, response); }));}
    void SetMessageAllocatorFor_someoneIsRobotHold(
        ::grpc::MessageAllocator< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_someoneIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* someoneIsRobotHold(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_someoneIsFixed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_someoneIsFixed() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* response) { return this->someoneIsFixed(context, request, response); }));}
    void SetMessageAllocatorFor_someoneIsFixed(
        ::grpc::MessageAllocator< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_someoneIsFixed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsFixed(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* someoneIsFixed(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCurrentWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCurrentWobjParam() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* response) { return this->GetCurrentWobjParam(context, request, response); }));}
    void SetMessageAllocatorFor_GetCurrentWobjParam(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCurrentWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCurrentWobjParam(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetWobjParam() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::UInt32Value* request, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* response) { return this->GetWobjParam(context, request, response); }));}
    void SetMessageAllocatorFor_GetWobjParam(
        ::grpc::MessageAllocator< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetWobjParam(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetWobjParam() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request, ::google::protobuf::BoolValue>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* request, ::google::protobuf::BoolValue* response) { return this->SetWobjParam(context, request, response); }));}
    void SetMessageAllocatorFor_SetWobjParam(
        ::grpc::MessageAllocator< ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request, ::google::protobuf::BoolValue>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request, ::google::protobuf::BoolValue>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetWobjParam(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetWobjParam(
      ::grpc::CallbackServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getCurrentId<WithCallbackMethod_SetCurrentId<WithCallbackMethod_currentIsRobotHold<WithCallbackMethod_someoneIsRobotHold<WithCallbackMethod_someoneIsFixed<WithCallbackMethod_GetCurrentWobjParam<WithCallbackMethod_GetWobjParam<WithCallbackMethod_SetWobjParam<Service > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getCurrentId() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetCurrentId() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_currentIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_currentIsRobotHold() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_currentIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status currentIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_someoneIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_someoneIsRobotHold() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_someoneIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_someoneIsFixed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_someoneIsFixed() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_someoneIsFixed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsFixed(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCurrentWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCurrentWobjParam() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_GetCurrentWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetWobjParam() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_GetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetWobjParam() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_SetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetWobjParam(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getCurrentId() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetCurrentId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetCurrentId() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetCurrentId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_currentIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_currentIsRobotHold() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_currentIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status currentIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcurrentIsRobotHold(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_someoneIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_someoneIsRobotHold() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_someoneIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsomeoneIsRobotHold(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_someoneIsFixed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_someoneIsFixed() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_someoneIsFixed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsFixed(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsomeoneIsFixed(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCurrentWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCurrentWobjParam() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_GetCurrentWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCurrentWobjParam(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetWobjParam() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_GetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWobjParam(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetWobjParam() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_SetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetWobjParam(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetWobjParam(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getCurrentId() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getCurrentId(context, request, response); }));
    }
    ~WithRawCallbackMethod_getCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getCurrentId(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetCurrentId() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetCurrentId(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetCurrentId(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_currentIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_currentIsRobotHold() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->currentIsRobotHold(context, request, response); }));
    }
    ~WithRawCallbackMethod_currentIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status currentIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* currentIsRobotHold(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_someoneIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_someoneIsRobotHold() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->someoneIsRobotHold(context, request, response); }));
    }
    ~WithRawCallbackMethod_someoneIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* someoneIsRobotHold(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_someoneIsFixed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_someoneIsFixed() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->someoneIsFixed(context, request, response); }));
    }
    ~WithRawCallbackMethod_someoneIsFixed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status someoneIsFixed(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* someoneIsFixed(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCurrentWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCurrentWobjParam() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCurrentWobjParam(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCurrentWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCurrentWobjParam(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetWobjParam() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetWobjParam(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetWobjParam(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetWobjParam() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetWobjParam(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetWobjParam(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetWobjParam(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getCurrentId() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::google::protobuf::UInt32Value>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::google::protobuf::UInt32Value>* streamer) {
                       return this->StreamedgetCurrentId(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::google::protobuf::UInt32Value* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetCurrentId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::google::protobuf::UInt32Value>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetCurrentId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetCurrentId() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::UInt32Value, ::google::protobuf::BoolValue>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::UInt32Value, ::google::protobuf::BoolValue>* streamer) {
                       return this->StreamedSetCurrentId(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetCurrentId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetCurrentId(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetCurrentId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::UInt32Value,::google::protobuf::BoolValue>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_currentIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_currentIsRobotHold() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* streamer) {
                       return this->StreamedcurrentIsRobotHold(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_currentIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status currentIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcurrentIsRobotHold(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::InoRobBusinessGrpc::WobjGrpc_currentIsRobotHold_Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_someoneIsRobotHold : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_someoneIsRobotHold() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* streamer) {
                       return this->StreamedsomeoneIsRobotHold(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_someoneIsRobotHold() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status someoneIsRobotHold(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsomeoneIsRobotHold(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::UInt32Value,::InoRobBusinessGrpc::WobjGrpc_someoneIsRobotHold_Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_someoneIsFixed : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_someoneIsFixed() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* streamer) {
                       return this->StreamedsomeoneIsFixed(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_someoneIsFixed() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status someoneIsFixed(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsomeoneIsFixed(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::UInt32Value,::InoRobBusinessGrpc::WobjGrpc_someoneIsFixed_Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCurrentWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCurrentWobjParam() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* streamer) {
                       return this->StreamedGetCurrentWobjParam(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCurrentWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCurrentWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCurrentWobjParam(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::InoRobBusinessGrpc::WobjGrpc_GetCurrentWobjParam_Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetWobjParam() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::UInt32Value, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* streamer) {
                       return this->StreamedGetWobjParam(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetWobjParam(::grpc::ServerContext* /*context*/, const ::google::protobuf::UInt32Value* /*request*/, ::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetWobjParam(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::UInt32Value,::InoRobBusinessGrpc::WobjGrpc_GetWobjParam_Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetWobjParam : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetWobjParam() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request, ::google::protobuf::BoolValue>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request, ::google::protobuf::BoolValue>* streamer) {
                       return this->StreamedSetWobjParam(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetWobjParam() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetWobjParam(::grpc::ServerContext* /*context*/, const ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetWobjParam(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InoRobBusinessGrpc::WobjGrpc_SetWobjParam_Request,::google::protobuf::BoolValue>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getCurrentId<WithStreamedUnaryMethod_SetCurrentId<WithStreamedUnaryMethod_currentIsRobotHold<WithStreamedUnaryMethod_someoneIsRobotHold<WithStreamedUnaryMethod_someoneIsFixed<WithStreamedUnaryMethod_GetCurrentWobjParam<WithStreamedUnaryMethod_GetWobjParam<WithStreamedUnaryMethod_SetWobjParam<Service > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getCurrentId<WithStreamedUnaryMethod_SetCurrentId<WithStreamedUnaryMethod_currentIsRobotHold<WithStreamedUnaryMethod_someoneIsRobotHold<WithStreamedUnaryMethod_someoneIsFixed<WithStreamedUnaryMethod_GetCurrentWobjParam<WithStreamedUnaryMethod_GetWobjParam<WithStreamedUnaryMethod_SetWobjParam<Service > > > > > > > > StreamedService;
};

}  // namespace InoRobBusinessGrpc


#endif  // GRPC_WobjGrpc_2eproto__INCLUDED
